//! Read-only installation planning and the single execution boundary.

#[cfg(test)]
use crate::catalog::catalog_skills;
use crate::catalog::{skill_catalog_path, skill_frontmatter, validate_skill_name};
use crate::digest::directory_digest;
use crate::domain::{
    CatalogContents, CatalogSkill, Destination, InstallMarker, InstallOwnership, SkillStatus,
    SourceDefinition, BUILT_IN_SOURCE_ID, CATALOG_SOURCE, MARKER_FILE,
};
use crate::ipc::{AutoUpdateReport, ReplaceUnmanagedResult, SkillReference, SkillUpdateFailure};
use crate::sources::{copy_directory, temporary_path, validate_repository_url, SourceCatalog};
use crate::{fs_retry, parallel};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

pub(crate) const LEGACY_MARKER_CONTENTS: &str =
    "Managed by Skill Manager. Do not edit this file.\n";
const MARKER_VERSION: u8 = 2;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum InstallationMode {
    Install,
    Uninstall,
}

impl InstallationMode {
    pub(crate) fn noun(self) -> &'static str {
        match self {
            Self::Install => "installation",
            Self::Uninstall => "removal",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum PlanAction {
    Install,
    Update,
    Installed,
    Uninstall,
    NotInstalled,
    Adopt,
    Conflict,
    Modified,
    SourceConflict,
}

impl PlanAction {
    pub(crate) fn needs_attention(self) -> bool {
        matches!(
            self,
            Self::Adopt | Self::Conflict | Self::Modified | Self::SourceConflict
        )
    }

    pub(crate) fn is_actionable(self) -> bool {
        matches!(self, Self::Install | Self::Update | Self::Uninstall)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct PlannedChange {
    pub(crate) name: String,
    pub(crate) destination: Destination,
    pub(crate) action: PlanAction,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct InstallationPlan {
    pub(crate) source_id: String,
    pub(crate) has_conflicts: bool,
    pub(crate) changes: Vec<PlannedChange>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct ExecutionFailure {
    pub(crate) name: String,
    pub(crate) message: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct ExecutionResult {
    pub(crate) completed: Vec<PlannedChange>,
    pub(crate) failures: Vec<ExecutionFailure>,
}

fn action_for(status: SkillStatus, mode: InstallationMode) -> PlanAction {
    match (mode, status) {
        (InstallationMode::Install, SkillStatus::Available) => PlanAction::Install,
        (InstallationMode::Install, SkillStatus::Installed | SkillStatus::Removed) => {
            PlanAction::Installed
        }
        (InstallationMode::Install, SkillStatus::UpdateAvailable) => PlanAction::Update,
        (InstallationMode::Uninstall, SkillStatus::Available) => PlanAction::NotInstalled,
        (
            InstallationMode::Uninstall,
            SkillStatus::Installed | SkillStatus::Removed | SkillStatus::UpdateAvailable,
        ) => PlanAction::Uninstall,
        (_, SkillStatus::UnmanagedMatch) => PlanAction::Adopt,
        (_, SkillStatus::Conflict) => PlanAction::Conflict,
        (_, SkillStatus::Modified) => PlanAction::Modified,
        (_, SkillStatus::SourceConflict) => PlanAction::SourceConflict,
    }
}

pub(crate) fn plan_source<F>(
    catalog: &CatalogContents,
    source: &SourceDefinition,
    mode: InstallationMode,
    status_for: F,
) -> Result<InstallationPlan, String>
where
    F: Fn(&CatalogSkill, &Destination) -> SkillStatus,
{
    let mut changes = Vec::with_capacity(catalog.skills.len());
    for skill in catalog.skills.values() {
        let destination = Destination::user_skill(&skill.name)?;
        changes.push(PlannedChange {
            name: skill.name.clone(),
            action: action_for(status_for(skill, &destination), mode),
            destination,
        });
    }
    let has_conflicts = changes.iter().any(|change| change.action.needs_attention());
    Ok(InstallationPlan {
        source_id: source.id.clone(),
        has_conflicts,
        changes,
    })
}

pub(crate) fn execute_plan<F>(
    plan: InstallationPlan,
    mode: InstallationMode,
    mut apply: F,
) -> Result<ExecutionResult, String>
where
    F: FnMut(&PlannedChange) -> Result<(), String>,
{
    if plan.has_conflicts {
        return Err(format!(
            "Bulk {} was not started because one or more skills need manual attention.",
            mode.noun()
        ));
    }

    let mut completed = Vec::new();
    let mut failures = Vec::new();
    for change in plan.changes {
        if !change.action.is_actionable() {
            continue;
        }
        match apply(&change) {
            Ok(()) => completed.push(change),
            Err(message) => failures.push(ExecutionFailure {
                name: change.name,
                message,
            }),
        }
    }
    Ok(ExecutionResult {
        completed,
        failures,
    })
}

pub(crate) fn install_root(home: &Path) -> PathBuf {
    Destination::user_skills_root().resolve(home)
}

pub(crate) fn backup_root(home: &Path) -> PathBuf {
    home.join(".agents").join(".skill-manager-backups")
}

pub(crate) fn current_epoch_seconds() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

pub(crate) fn valid_digest(digest: &str) -> bool {
    digest.len() == 64
        && digest
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

pub(crate) fn install_ownership(target: &Path) -> InstallOwnership {
    let Ok(contents) = fs::read_to_string(target.join(MARKER_FILE)) else {
        return InstallOwnership::Unmanaged;
    };
    let normalized = contents
        .strip_prefix('\u{feff}')
        .unwrap_or(&contents)
        .replace("\r\n", "\n");

    if normalized == LEGACY_MARKER_CONTENTS {
        return InstallOwnership::Legacy;
    }

    match serde_json::from_str::<InstallMarker>(&normalized) {
        Ok(marker) if marker_source_id(&marker).is_some() && valid_digest(&marker.skill_digest) => {
            InstallOwnership::Managed(marker)
        }
        _ => InstallOwnership::Unmanaged,
    }
}

pub(crate) fn marker_source_id(marker: &InstallMarker) -> Option<&str> {
    if marker.version == MARKER_VERSION {
        let source_id = marker.source_id.as_deref()?;
        if source_id == BUILT_IN_SOURCE_ID && marker.source == CATALOG_SOURCE {
            return Some(source_id);
        }
        validate_repository_url(&marker.source)
            .ok()
            .filter(|identity| identity.source_key == source_id)
            .map(|_| source_id)
    } else if marker.version == 1 && marker.source_id.is_none() && marker.source == CATALOG_SOURCE {
        Some(BUILT_IN_SOURCE_ID)
    } else {
        None
    }
}

pub(crate) fn path_entry_exists(path: &Path) -> bool {
    fs::symlink_metadata(path).is_ok()
}

pub(crate) fn unmanaged_status(target: &Path, catalog_digest: Option<&str>) -> SkillStatus {
    let is_real_directory =
        fs::symlink_metadata(target).is_ok_and(|metadata| metadata.file_type().is_dir());
    if !is_real_directory {
        return SkillStatus::Conflict;
    }

    match (catalog_digest, directory_digest(target)) {
        (Some(catalog_digest), Ok(installed_digest)) if installed_digest == catalog_digest => {
            SkillStatus::UnmanagedMatch
        }
        _ => SkillStatus::Conflict,
    }
}

pub(crate) fn installation_status(
    target: &Path,
    catalog_digest: Option<&str>,
    source_id: &str,
) -> SkillStatus {
    if !path_entry_exists(target) {
        return SkillStatus::Available;
    }

    match install_ownership(target) {
        InstallOwnership::Unmanaged => unmanaged_status(target, catalog_digest),
        InstallOwnership::Legacy if source_id == BUILT_IN_SOURCE_ID => match catalog_digest {
            Some(_) => SkillStatus::UpdateAvailable,
            None => SkillStatus::Removed,
        },
        InstallOwnership::Legacy => SkillStatus::SourceConflict,
        InstallOwnership::Managed(marker)
            if marker_source_id(&marker).is_some_and(|owner| owner == source_id) =>
        {
            match directory_digest(target) {
                Ok(installed_digest) if installed_digest == marker.skill_digest => {
                    match catalog_digest {
                        Some(digest) if digest == installed_digest => SkillStatus::Installed,
                        Some(_) => SkillStatus::UpdateAvailable,
                        None => SkillStatus::Removed,
                    }
                }
                _ => SkillStatus::Modified,
            }
        }
        InstallOwnership::Managed(_) => SkillStatus::SourceConflict,
    }
}

pub(crate) fn installation_status_without_catalog(target: &Path, source_id: &str) -> SkillStatus {
    match install_ownership(target) {
        InstallOwnership::Unmanaged => SkillStatus::Conflict,
        InstallOwnership::Legacy if source_id == BUILT_IN_SOURCE_ID => SkillStatus::Installed,
        InstallOwnership::Legacy => SkillStatus::SourceConflict,
        InstallOwnership::Managed(marker)
            if marker_source_id(&marker).is_some_and(|owner| owner == source_id) =>
        {
            match directory_digest(target) {
                Ok(installed_digest) if installed_digest == marker.skill_digest => {
                    SkillStatus::Installed
                }
                _ => SkillStatus::Modified,
            }
        }
        InstallOwnership::Managed(_) => SkillStatus::SourceConflict,
    }
}

pub(crate) fn write_install_marker(
    target: &Path,
    source: &SourceDefinition,
    digest: &str,
) -> Result<(), String> {
    let marker = InstallMarker {
        version: MARKER_VERSION,
        source_id: Some(source.id.clone()),
        source: source.url.clone(),
        skill_digest: digest.to_string(),
    };
    let mut contents = serde_json::to_string_pretty(&marker)
        .map_err(|error| format!("Could not create the ownership marker: {error}"))?;
    contents.push('\n');
    fs::write(target.join(MARKER_FILE), contents)
        .map_err(|error| format!("Could not write the ownership marker: {error}"))
}

pub(crate) fn catalog_skill_at(catalog: &Path, name: &str) -> Result<CatalogSkill, String> {
    validate_skill_name(name)?;
    let source = skill_catalog_path(catalog, name);
    if !source.is_dir() {
        return Err(format!("Unknown skill: {name}"));
    }
    if source.join(MARKER_FILE).exists() {
        return Err(format!(
            "{} contains the reserved marker file",
            source.display()
        ));
    }

    let (declared_name, description) = skill_frontmatter(&source)?;
    if declared_name != name {
        return Err(format!("{name} has invalid catalog metadata."));
    }
    let digest = directory_digest(&source)?;
    Ok(CatalogSkill {
        name: name.to_string(),
        description,
        digest,
    })
}

pub(crate) fn replace_skill_at(
    home: &Path,
    catalog: &Path,
    source_definition: &SourceDefinition,
    skill: &CatalogSkill,
) -> Result<(), String> {
    let name = &skill.name;
    let source = skill_catalog_path(catalog, name);
    let root = install_root(home);
    let target = root.join(name);

    fs::create_dir_all(&root)
        .map_err(|error| format!("Could not create {}: {error}", root.display()))?;
    let staging = temporary_path(&root, &format!("{name}-installing"));
    let result = (|| {
        copy_directory(&source, &staging)?;
        write_install_marker(&staging, source_definition, &skill.digest)?;

        if !target.exists() {
            return fs_retry::rename(&staging, &target)
                .map_err(|error| format!("Could not finish installing {name}: {error}"));
        }

        let backup = temporary_path(&root, &format!("{name}-previous"));
        fs_retry::rename(&target, &backup)
            .map_err(|error| format!("Could not prepare {name} for update: {error}"))?;
        if let Err(error) = fs_retry::rename(&staging, &target) {
            let restore = fs_retry::rename(&backup, &target);
            return match restore {
                Ok(()) => Err(format!("Could not finish updating {name}: {error}")),
                Err(restore_error) => Err(format!(
                    "Could not finish updating {name} ({error}) or restore the installed copy ({restore_error})."
                )),
            };
        }
        fs_retry::remove_dir_all(&backup).map_err(|error| {
            format!("{name} updated, but its previous copy could not be removed: {error}")
        })
    })();

    if staging.exists() {
        let _ = fs_retry::remove_dir_all(&staging);
    }

    result
}

pub(crate) fn next_backup_path(home: &Path, name: &str) -> Result<PathBuf, String> {
    let parent = backup_root(home).join(name);
    fs::create_dir_all(&parent)
        .map_err(|error| format!("Could not create {}: {error}", parent.display()))?;
    let timestamp = current_epoch_seconds();

    for suffix in 0..10_000_u16 {
        let directory_name = if suffix == 0 {
            timestamp.to_string()
        } else {
            format!("{timestamp}-{suffix}")
        };
        let candidate = parent.join(directory_name);
        if !path_entry_exists(&candidate) {
            return Ok(candidate);
        }
    }

    Err(format!(
        "Could not choose a unique backup path in {}.",
        parent.display()
    ))
}

pub(crate) fn activate_unmanaged_replacement(
    name: &str,
    target: &Path,
    staging: &Path,
    backup: &Path,
) -> Result<(), String> {
    fs_retry::rename(target, backup)
        .map_err(|error| format!("Could not back up the existing {name} skill: {error}"))?;

    if let Err(error) = fs_retry::rename(staging, target) {
        let restore = fs_retry::rename(backup, target);
        return match restore {
            Ok(()) => Err(format!(
                "Could not finish replacing {name}; the original skill was restored: {error}"
            )),
            Err(restore_error) => Err(format!(
                "Could not finish replacing {name} ({error}) or restore the original skill ({restore_error}). Its backup remains at {}.",
                backup.display()
            )),
        };
    }

    Ok(())
}

pub(crate) fn adopt_at_source(
    home: &Path,
    catalog: &Path,
    source: &SourceDefinition,
    name: &str,
) -> Result<(), String> {
    let skill = catalog_skill_at(catalog, name)?;
    let target = install_root(home).join(name);

    if !path_entry_exists(&target) {
        return Err(format!("{name} no longer exists at {}.", target.display()));
    }
    if !matches!(install_ownership(&target), InstallOwnership::Unmanaged) {
        return Err(format!(
            "{} is already managed by Skill Manager.",
            target.display()
        ));
    }
    if unmanaged_status(&target, Some(&skill.digest)) != SkillStatus::UnmanagedMatch {
        return Err(format!(
            "{} does not exactly match the skillbook copy. It was not adopted.",
            target.display()
        ));
    }

    write_install_marker(&target, source, &skill.digest)
}

pub(crate) fn replace_unmanaged_at_source(
    home: &Path,
    catalog: &Path,
    source: &SourceDefinition,
    name: &str,
) -> Result<ReplaceUnmanagedResult, String> {
    let skill = catalog_skill_at(catalog, name)?;
    let root = install_root(home);
    let target = root.join(name);

    if !path_entry_exists(&target) {
        return Err(format!("{name} no longer exists at {}.", target.display()));
    }
    if !matches!(install_ownership(&target), InstallOwnership::Unmanaged) {
        return Err(format!(
            "{} is managed by Skill Manager and cannot be replaced as an unmanaged conflict.",
            target.display()
        ));
    }
    if unmanaged_status(&target, Some(&skill.digest)) == SkillStatus::UnmanagedMatch {
        return Err(format!(
            "{} exactly matches skillbook. Use Manage instead of Replace.",
            target.display()
        ));
    }

    fs::create_dir_all(&root)
        .map_err(|error| format!("Could not create {}: {error}", root.display()))?;
    let staging = temporary_path(&root, &format!("{name}-installing"));
    let result = (|| {
        copy_directory(&catalog.join(name), &staging)?;
        write_install_marker(&staging, source, &skill.digest)?;

        if !path_entry_exists(&target) {
            return Err(format!(
                "{name} disappeared before it could be backed up. Nothing was installed."
            ));
        }
        if !matches!(install_ownership(&target), InstallOwnership::Unmanaged) {
            return Err(format!(
                "{} became managed before it could be replaced. Nothing was changed.",
                target.display()
            ));
        }

        let backup = next_backup_path(home, name)?;
        activate_unmanaged_replacement(name, &target, &staging, &backup)?;
        Ok(ReplaceUnmanagedResult {
            backup_path: backup.display().to_string(),
        })
    })();

    if path_entry_exists(&staging) {
        let _ = fs_retry::remove_dir_all(&staging);
    }

    result
}

pub(crate) fn install_catalog_skill_at(
    home: &Path,
    catalog: &Path,
    source: &SourceDefinition,
    skill: &CatalogSkill,
) -> Result<(), String> {
    let target = install_root(home).join(&skill.name);

    if path_entry_exists(&target) {
        match installation_status(&target, Some(&skill.digest), &source.id) {
            SkillStatus::Installed => {
                return Err(format!("{} is already installed.", skill.name));
            }
            SkillStatus::UpdateAvailable => {}
            SkillStatus::Modified => {
                return Err(format!(
                    "{} contains local changes. Skill Manager will not overwrite it.",
                    target.display()
                ));
            }
            SkillStatus::Available
            | SkillStatus::Removed
            | SkillStatus::UnmanagedMatch
            | SkillStatus::Conflict
            | SkillStatus::SourceConflict => {
                return Err(format!(
                    "{} already exists. Skill Manager will not overwrite it.",
                    target.display()
                ));
            }
        }
    }

    replace_skill_at(home, catalog, source, skill)
}

pub(crate) fn install_at_source(
    home: &Path,
    catalog: &Path,
    source: &SourceDefinition,
    name: &str,
) -> Result<(), String> {
    let skill = catalog_skill_at(catalog, name)?;
    install_catalog_skill_at(home, catalog, source, &skill)
}

#[cfg(test)]
pub(crate) fn install_at(home: &Path, catalog: &Path, name: &str) -> Result<(), String> {
    install_at_source(home, catalog, &SourceDefinition::built_in(), name)
}

#[cfg(test)]
pub(crate) fn adopt_at(home: &Path, catalog: &Path, name: &str) -> Result<(), String> {
    adopt_at_source(home, catalog, &SourceDefinition::built_in(), name)
}

#[cfg(test)]
pub(crate) fn replace_unmanaged_at(
    home: &Path,
    catalog: &Path,
    name: &str,
) -> Result<ReplaceUnmanagedResult, String> {
    replace_unmanaged_at_source(home, catalog, &SourceDefinition::built_in(), name)
}

/// What an automatic update should do with one installed skill. Reaching this
/// verdict is pure inspection — a marker read and, for a managed skill, a
/// directory hash — so it is decided for every skill at once and only the
/// replacements that follow happen one at a time.
enum AutoUpdate {
    /// Not installed, not managed by Skill Manager, or owned by another source.
    Leave,
    UpToDate,
    Legacy,
    Modified,
    Replace,
    Failed(String),
}

fn auto_update_for(root: &Path, source: &SourceDefinition, skill: &CatalogSkill) -> AutoUpdate {
    let target = root.join(&skill.name);
    if !path_entry_exists(&target) {
        return AutoUpdate::Leave;
    }

    match install_ownership(&target) {
        InstallOwnership::Unmanaged => AutoUpdate::Leave,
        InstallOwnership::Legacy if source.is_built_in() => AutoUpdate::Legacy,
        InstallOwnership::Legacy => AutoUpdate::Leave,
        InstallOwnership::Managed(marker) => {
            if marker_source_id(&marker) != Some(source.id.as_str()) {
                return AutoUpdate::Leave;
            }
            match directory_digest(&target) {
                Err(message) => AutoUpdate::Failed(message),
                Ok(installed) if installed != marker.skill_digest => AutoUpdate::Modified,
                Ok(installed) if installed != skill.digest => AutoUpdate::Replace,
                Ok(_) => AutoUpdate::UpToDate,
            }
        }
    }
}

pub(crate) fn reconcile_source_skills(
    home: &Path,
    catalog: &Path,
    source: &SourceDefinition,
    catalog_skills: &BTreeMap<String, CatalogSkill>,
) -> Result<AutoUpdateReport, String> {
    let root = install_root(home);
    let skills = catalog_skills.values().collect::<Vec<_>>();
    let verdicts = parallel::map(&skills, |skill| auto_update_for(&root, source, skill));
    let mut report = AutoUpdateReport::default();

    for (skill, verdict) in skills.iter().zip(verdicts) {
        let reference = || SkillReference {
            source_id: source.id.clone(),
            name: skill.name.clone(),
        };
        let failure = |message| SkillUpdateFailure {
            source_id: source.id.clone(),
            name: skill.name.clone(),
            message,
        };
        match verdict {
            AutoUpdate::Leave | AutoUpdate::UpToDate => {}
            AutoUpdate::Legacy => report.skipped_legacy_skills.push(reference()),
            AutoUpdate::Modified => report.skipped_modified_skills.push(reference()),
            AutoUpdate::Failed(message) => report.failed_skills.push(failure(message)),
            AutoUpdate::Replace => match replace_skill_at(home, catalog, source, skill) {
                Ok(()) => report.updated_skills.push(reference()),
                Err(message) => report.failed_skills.push(failure(message)),
            },
        }
    }

    Ok(report)
}

pub(crate) fn merge_auto_update_report(target: &mut AutoUpdateReport, source: AutoUpdateReport) {
    target.updated_skills.extend(source.updated_skills);
    target
        .skipped_modified_skills
        .extend(source.skipped_modified_skills);
    target
        .skipped_legacy_skills
        .extend(source.skipped_legacy_skills);
    target.failed_skills.extend(source.failed_skills);
}

pub(crate) fn reconcile_catalogs(
    home: &Path,
    catalogs: &[SourceCatalog],
) -> Result<AutoUpdateReport, String> {
    let mut report = AutoUpdateReport::default();
    for catalog in catalogs {
        let Some(path) = catalog.path.as_deref() else {
            continue;
        };
        let source_report =
            reconcile_source_skills(home, path, &catalog.definition, &catalog.skills)?;
        merge_auto_update_report(&mut report, source_report);
    }
    Ok(report)
}

#[cfg(test)]
pub(crate) fn auto_update_at(home: &Path, catalog: &Path) -> Result<AutoUpdateReport, String> {
    let skills = catalog_skills(catalog)?;
    reconcile_source_skills(home, catalog, &SourceDefinition::built_in(), &skills)
}

pub(crate) fn uninstall_at_source(home: &Path, source_id: &str, name: &str) -> Result<(), String> {
    validate_skill_name(name)?;
    let target = install_root(home).join(name);

    if !path_entry_exists(&target) {
        return Err(format!("{name} is not installed."));
    }

    match install_ownership(&target) {
        InstallOwnership::Unmanaged => {
            return Err(format!(
                "{} is not managed by Skill Manager. It was not removed.",
                target.display()
            ));
        }
        InstallOwnership::Legacy if source_id == BUILT_IN_SOURCE_ID => {}
        InstallOwnership::Legacy => {
            return Err(format!(
                "{} is not managed by the requested source. It was not removed.",
                target.display()
            ));
        }
        InstallOwnership::Managed(marker) => {
            if marker_source_id(&marker) != Some(source_id) {
                return Err(format!(
                    "{} is managed by a different source. It was not removed.",
                    target.display()
                ));
            }
            let digest = directory_digest(&target)?;
            if digest != marker.skill_digest {
                return Err(format!(
                    "{} contains local changes. It was not removed.",
                    target.display()
                ));
            }
        }
    }

    fs_retry::remove_dir_all(&target)
        .map_err(|error| format!("Could not uninstall {name}: {error}"))
}

#[cfg(test)]
pub(crate) fn uninstall_at(home: &Path, name: &str) -> Result<(), String> {
    uninstall_at_source(home, BUILT_IN_SOURCE_ID, name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::CatalogError;
    use std::cell::Cell;
    use std::collections::BTreeMap;

    fn source() -> SourceDefinition {
        SourceDefinition {
            id: "source-test".to_string(),
            name: "test".to_string(),
            url: "https://example.com/test".to_string(),
        }
    }

    fn catalog() -> CatalogContents {
        CatalogContents {
            skills: BTreeMap::from([(
                "example".to_string(),
                CatalogSkill {
                    name: "example".to_string(),
                    description: "Example".to_string(),
                    digest: "digest".to_string(),
                },
            )]),
            errors: Vec::<CatalogError>::new(),
        }
    }

    #[test]
    fn planner_is_read_only_and_produces_anchored_changes() {
        let inspected = Cell::new(0);
        let plan = plan_source(
            &catalog(),
            &source(),
            InstallationMode::Install,
            |_, destination| {
                inspected.set(inspected.get() + 1);
                assert_eq!(
                    destination.relative_path(),
                    std::path::Path::new(".agents/skills/example")
                );
                SkillStatus::Available
            },
        )
        .expect("plan");
        assert_eq!(inspected.get(), 1);
        assert_eq!(plan.changes[0].action, PlanAction::Install);
    }

    #[test]
    fn executor_never_mutates_a_plan_that_needs_attention() {
        let plan = plan_source(&catalog(), &source(), InstallationMode::Install, |_, _| {
            SkillStatus::Conflict
        })
        .expect("plan");
        let calls = Cell::new(0);
        let result = execute_plan(plan, InstallationMode::Install, |_| {
            calls.set(calls.get() + 1);
            Ok(())
        });
        assert!(result.is_err());
        assert_eq!(calls.get(), 0);
    }
}
