use flate2::read::GzDecoder;
use reqwest::header::{HeaderValue, ACCEPT, ETAG, IF_NONE_MATCH};
use reqwest::StatusCode;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::ffi::OsStr;
use std::fs::{self, File, OpenOptions};
use std::io::{Cursor, Read, Write};
use std::path::{Component, Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tauri::{
    async_runtime::{self, Mutex},
    State,
};

const CATALOG_SOURCE: &str = "https://github.com/jacobragsdale/skillbook";
const CATALOG_REF_URL: &str =
    "https://api.github.com/repos/jacobragsdale/skillbook/git/ref/heads/main";
const CATALOG_METADATA_FILE: &str = ".skill-manager-catalog.json";
const CATALOG_METADATA_VERSION: u8 = 1;
const MAX_ARCHIVE_BYTES: u64 = 25 * 1024 * 1024;
const MAX_REF_RESPONSE_BYTES: u64 = 64 * 1024;
const MAX_EXTRACTED_BYTES: u64 = 50 * 1024 * 1024;
const MAX_CATALOG_FILES: usize = 2_000;
const MARKER_FILE: &str = ".skill-manager-managed";
const LEGACY_MARKER_CONTENTS: &str = "Managed by Skill Manager. Do not edit this file.\n";
const MARKER_VERSION: u8 = 1;

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct Skill {
    name: String,
    description: String,
    status: SkillStatus,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
enum SkillStatus {
    Available,
    Installed,
    UpdateAvailable,
    Removed,
    Modified,
    UnmanagedMatch,
    Conflict,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum CatalogStatus {
    Fresh,
    Cached,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct AppState {
    install_root: String,
    catalog_source: &'static str,
    catalog_status: CatalogStatus,
    catalog_message: Option<String>,
    catalog_commit: Option<String>,
    checked_at_epoch_seconds: u64,
    auto_update_report: AutoUpdateReport,
    skills: Vec<Skill>,
}

#[derive(Debug, Default, Serialize)]
#[serde(rename_all = "camelCase")]
struct AutoUpdateReport {
    updated_skills: Vec<String>,
    skipped_modified_skills: Vec<String>,
    skipped_legacy_skills: Vec<String>,
    failed_skills: Vec<SkillUpdateFailure>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct SkillUpdateFailure {
    name: String,
    message: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct ReplaceUnmanagedResult {
    backup_path: String,
}

#[derive(Debug)]
struct CatalogSkill {
    name: String,
    description: String,
    digest: String,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
struct InstallMarker {
    version: u8,
    source: String,
    skill_digest: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
struct CatalogMetadata {
    version: u8,
    source: String,
    commit_sha: String,
    etag: Option<String>,
}

#[derive(Debug, Deserialize)]
struct GitHubReference {
    object: GitHubReferenceObject,
}

#[derive(Debug, Deserialize)]
struct GitHubReferenceObject {
    sha: String,
}

enum CommitCheck {
    NotModified,
    Current(CatalogMetadata),
}

enum PreparedCatalog {
    Current(String),
    Staged {
        commit_sha: String,
        path: PathBuf,
        skills: BTreeMap<String, CatalogSkill>,
    },
}

enum InstallOwnership {
    Unmanaged,
    Legacy,
    Managed(InstallMarker),
}

struct RuntimeState {
    catalog_lock: Mutex<()>,
    sync_lock: Mutex<()>,
    github_client: reqwest::Client,
}

impl RuntimeState {
    fn new() -> Result<Self, String> {
        Ok(Self {
            catalog_lock: Mutex::new(()),
            sync_lock: Mutex::new(()),
            github_client: github_client()?,
        })
    }
}

async fn run_blocking<T, F>(context: &'static str, task: F) -> Result<T, String>
where
    T: Send + 'static,
    F: FnOnce() -> Result<T, String> + Send + 'static,
{
    async_runtime::spawn_blocking(task)
        .await
        .map_err(|error| format!("{context} worker failed: {error}"))?
}

fn home_dir() -> Result<PathBuf, String> {
    dirs::home_dir().ok_or_else(|| "Could not find your home directory.".to_string())
}

fn cache_base_dir() -> Result<PathBuf, String> {
    dirs::cache_dir()
        .map(|directory| directory.join("skill-manager"))
        .ok_or_else(|| "Could not find your cache directory.".to_string())
}

fn catalog_dir(cache_base: &Path) -> PathBuf {
    cache_base.join("catalog")
}

fn catalog_metadata_path(catalog: &Path) -> PathBuf {
    catalog.join(CATALOG_METADATA_FILE)
}

fn install_root(home: &Path) -> PathBuf {
    home.join(".agents").join("skills")
}

fn backup_root(home: &Path) -> PathBuf {
    home.join(".agents").join(".skill-manager-backups")
}

fn current_epoch_seconds() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

fn valid_commit_sha(commit_sha: &str) -> bool {
    commit_sha.len() == 40
        && commit_sha
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn catalog_archive_url(commit_sha: &str) -> Result<String, String> {
    if !valid_commit_sha(commit_sha) {
        return Err("GitHub returned an invalid skillbook commit SHA.".to_string());
    }

    Ok(format!("{CATALOG_SOURCE}/archive/{commit_sha}.tar.gz"))
}

fn read_catalog_metadata(catalog: &Path) -> Option<CatalogMetadata> {
    let contents = fs::read(catalog_metadata_path(catalog)).ok()?;
    let metadata = serde_json::from_slice::<CatalogMetadata>(&contents).ok()?;

    if metadata.version == CATALOG_METADATA_VERSION
        && metadata.source == CATALOG_SOURCE
        && valid_commit_sha(&metadata.commit_sha)
        && metadata
            .etag
            .as_ref()
            .is_none_or(|etag| etag.len() <= 1024 && HeaderValue::from_str(etag).is_ok())
    {
        Some(metadata)
    } else {
        None
    }
}

fn write_catalog_metadata(catalog: &Path, metadata: &CatalogMetadata) -> Result<(), String> {
    let mut contents = serde_json::to_vec_pretty(metadata)
        .map_err(|error| format!("Could not create the catalog metadata: {error}"))?;
    contents.push(b'\n');
    fs::write(catalog_metadata_path(catalog), contents)
        .map_err(|error| format!("Could not write the catalog metadata: {error}"))
}

fn is_windows_reserved_name(name: &str) -> bool {
    let stem = name.split('.').next().unwrap_or(name);
    let uppercase = stem.to_uppercase();

    matches!(uppercase.as_str(), "CON" | "PRN" | "AUX" | "NUL")
        || ["COM", "LPT"].iter().any(|prefix| {
            uppercase.strip_prefix(prefix).is_some_and(|suffix| {
                matches!(
                    suffix,
                    "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "¹" | "²" | "³"
                )
            })
        })
}

fn validate_portable_path_component(component: &OsStr, path: &Path) -> Result<(), String> {
    let name = component
        .to_str()
        .ok_or_else(|| format!("Archive path is not UTF-8: {}", path.display()))?;
    let has_windows_reserved_character = name.chars().any(|character| {
        character <= '\u{1f}'
            || matches!(
                character,
                '<' | '>' | ':' | '"' | '/' | '\\' | '|' | '?' | '*'
            )
    });
    let too_long_for_windows = name.encode_utf16().count() > 255;

    if name.ends_with([' ', '.'])
        || has_windows_reserved_character
        || is_windows_reserved_name(name)
        || too_long_for_windows
    {
        Err(format!(
            "Archive path is not portable to Windows: {}",
            path.display()
        ))
    } else {
        Ok(())
    }
}

fn validate_skill_name(name: &str) -> Result<(), String> {
    let valid = !name.is_empty()
        && name
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
        && !name.starts_with('-')
        && !name.ends_with('-')
        && !name.contains("--")
        && !is_windows_reserved_name(name);

    if valid {
        Ok(())
    } else {
        Err(format!("Invalid skill name: {name}"))
    }
}

fn frontmatter_value(contents: &str, key: &str) -> Option<String> {
    let frontmatter = contents.strip_prefix("---\n")?.split_once("\n---")?.0;
    let prefix = format!("{key}:");

    frontmatter.lines().find_map(|line| {
        line.strip_prefix(&prefix)
            .map(str::trim)
            .map(|value| value.trim_matches(['"', '\'']).to_string())
            .filter(|value| !value.is_empty())
    })
}

fn skill_frontmatter(skill: &Path) -> Result<(String, String), String> {
    let path = skill.join("SKILL.md");
    let bytes =
        fs::read(&path).map_err(|error| format!("Could not read {}: {error}", path.display()))?;
    let contents = String::from_utf8(bytes)
        .map_err(|error| format!("{} must be valid UTF-8: {error}", path.display()))?;
    let normalized = contents
        .strip_prefix('\u{feff}')
        .unwrap_or(&contents)
        .replace("\r\n", "\n");
    let name = frontmatter_value(&normalized, "name")
        .ok_or_else(|| format!("{} is missing a name", path.display()))?;
    let description = frontmatter_value(&normalized, "description")
        .ok_or_else(|| format!("{} is missing a description", path.display()))?;

    Ok((name, description))
}

fn relative_path(root: &Path, path: &Path) -> Result<String, String> {
    let relative = path
        .strip_prefix(root)
        .map_err(|_| format!("{} is outside {}", path.display(), root.display()))?;
    let mut parts = Vec::new();

    for component in relative.components() {
        let Component::Normal(part) = component else {
            return Err(format!("{} has an invalid path", path.display()));
        };
        parts.push(
            part.to_str()
                .ok_or_else(|| format!("{} is not UTF-8", path.display()))?,
        );
    }

    Ok(parts.join("/"))
}

fn update_hash_field(hasher: &mut Sha256, value: &[u8]) {
    hasher.update((value.len() as u64).to_le_bytes());
    hasher.update(value);
}

fn hash_directory_entries(
    root: &Path,
    current: &Path,
    hasher: &mut Sha256,
    buffer: &mut [u8],
) -> Result<(), String> {
    let mut entries = fs::read_dir(current)
        .map_err(|error| format!("Could not read {}: {error}", current.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("Could not read {}: {error}", current.display()))?;
    entries.sort_by_key(fs::DirEntry::file_name);

    for entry in entries {
        if current == root && entry.file_name() == OsStr::new(MARKER_FILE) {
            continue;
        }

        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|error| format!("Could not inspect {}: {error}", path.display()))?;
        let relative = relative_path(root, &path)?;

        if file_type.is_dir() {
            hasher.update(b"directory");
            update_hash_field(hasher, relative.as_bytes());
            hash_directory_entries(root, &path, hasher, buffer)?;
        } else if file_type.is_file() {
            hasher.update(b"file");
            update_hash_field(hasher, relative.as_bytes());
            let mut file = File::open(&path)
                .map_err(|error| format!("Could not open {}: {error}", path.display()))?;
            let size = file
                .metadata()
                .map_err(|error| format!("Could not inspect {}: {error}", path.display()))?
                .len();
            hasher.update(size.to_le_bytes());

            loop {
                let read = file
                    .read(buffer)
                    .map_err(|error| format!("Could not read {}: {error}", path.display()))?;
                if read == 0 {
                    break;
                }
                hasher.update(&buffer[..read]);
            }
        } else {
            return Err(format!(
                "{} is not a regular file or directory",
                path.display()
            ));
        }
    }

    Ok(())
}

fn directory_digest(root: &Path) -> Result<String, String> {
    if !root.is_dir() {
        return Err(format!("{} is not a directory", root.display()));
    }

    let mut hasher = Sha256::new();
    let mut buffer = vec![0_u8; 64 * 1024];
    hash_directory_entries(root, root, &mut hasher, &mut buffer)?;
    let digest = hasher.finalize();
    let mut encoded = String::with_capacity(digest.len() * 2);
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in digest {
        encoded.push(HEX[(byte >> 4) as usize] as char);
        encoded.push(HEX[(byte & 0x0f) as usize] as char);
    }
    Ok(encoded)
}

fn valid_digest(digest: &str) -> bool {
    digest.len() == 64
        && digest
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn install_ownership(target: &Path) -> InstallOwnership {
    let Ok(contents) = fs::read_to_string(target.join(MARKER_FILE)) else {
        return InstallOwnership::Unmanaged;
    };
    let normalized = contents
        .strip_prefix('\u{feff}')
        .unwrap_or(&contents)
        .replace("\r\n", "\n");

    if normalized == LEGACY_MARKER_CONTENTS {
        return InstallOwnership::Legacy;
    }

    match serde_json::from_str::<InstallMarker>(&normalized) {
        Ok(marker)
            if marker.version == MARKER_VERSION
                && marker.source == CATALOG_SOURCE
                && valid_digest(&marker.skill_digest) =>
        {
            InstallOwnership::Managed(marker)
        }
        _ => InstallOwnership::Unmanaged,
    }
}

fn path_entry_exists(path: &Path) -> bool {
    fs::symlink_metadata(path).is_ok()
}

fn unmanaged_status(target: &Path, catalog_digest: Option<&str>) -> SkillStatus {
    let is_real_directory =
        fs::symlink_metadata(target).is_ok_and(|metadata| metadata.file_type().is_dir());
    if !is_real_directory {
        return SkillStatus::Conflict;
    }

    match (catalog_digest, directory_digest(target)) {
        (Some(catalog_digest), Ok(installed_digest)) if installed_digest == catalog_digest => {
            SkillStatus::UnmanagedMatch
        }
        _ => SkillStatus::Conflict,
    }
}

fn installation_status(target: &Path, catalog_digest: Option<&str>) -> SkillStatus {
    if !path_entry_exists(target) {
        return SkillStatus::Available;
    }

    match install_ownership(target) {
        InstallOwnership::Unmanaged => unmanaged_status(target, catalog_digest),
        InstallOwnership::Legacy => match catalog_digest {
            Some(_) => SkillStatus::UpdateAvailable,
            None => SkillStatus::Removed,
        },
        InstallOwnership::Managed(marker) => match directory_digest(target) {
            Ok(installed_digest) if installed_digest == marker.skill_digest => match catalog_digest
            {
                Some(digest) if digest == installed_digest => SkillStatus::Installed,
                Some(_) => SkillStatus::UpdateAvailable,
                None => SkillStatus::Removed,
            },
            _ => SkillStatus::Modified,
        },
    }
}

fn catalog_skills(root: &Path) -> Result<BTreeMap<String, CatalogSkill>, String> {
    let entries = fs::read_dir(root)
        .map_err(|error| format!("Could not read catalog {}: {error}", root.display()))?;
    let mut skills = BTreeMap::new();

    for entry in entries {
        let entry =
            entry.map_err(|error| format!("Could not read catalog {}: {error}", root.display()))?;
        let file_type = entry
            .file_type()
            .map_err(|error| format!("Could not inspect {}: {error}", entry.path().display()))?;
        if !file_type.is_dir() {
            continue;
        }

        let name = entry
            .file_name()
            .to_str()
            .ok_or_else(|| "A catalog skill has a non-UTF-8 name.".to_string())?
            .to_string();
        validate_skill_name(&name)?;
        let path = entry.path();

        if path.join(MARKER_FILE).exists() {
            return Err(format!(
                "{} contains the reserved marker file",
                path.display()
            ));
        }

        let (declared_name, description) = skill_frontmatter(&path)?;
        if declared_name != name {
            return Err(format!(
                "{} declares the name {declared_name}, expected {name}",
                path.join("SKILL.md").display()
            ));
        }

        let digest = directory_digest(&path)?;
        skills.insert(
            name.clone(),
            CatalogSkill {
                name,
                description,
                digest,
            },
        );
    }

    if skills.is_empty() {
        return Err("The skillbook catalog does not contain any skills.".to_string());
    }

    Ok(skills)
}

fn append_removed_skills(
    root: &Path,
    catalog_skills: &BTreeMap<String, CatalogSkill>,
    skills: &mut Vec<Skill>,
) -> Result<(), String> {
    if !root.is_dir() {
        return Ok(());
    }

    for entry in
        fs::read_dir(root).map_err(|error| format!("Could not read {}: {error}", root.display()))?
    {
        let entry = entry.map_err(|error| format!("Could not read {}: {error}", root.display()))?;
        if !entry
            .file_type()
            .map_err(|error| format!("Could not inspect {}: {error}", entry.path().display()))?
            .is_dir()
        {
            continue;
        }

        let Some(name) = entry.file_name().to_str().map(str::to_string) else {
            continue;
        };
        if validate_skill_name(&name).is_err() || catalog_skills.contains_key(&name) {
            continue;
        }
        if matches!(
            install_ownership(&entry.path()),
            InstallOwnership::Unmanaged
        ) {
            continue;
        }

        skills.push(Skill {
            name,
            description: "This skill is no longer available in skillbook.".to_string(),
            status: installation_status(&entry.path(), None),
        });
    }

    Ok(())
}

fn collect_skill_state(
    home: &Path,
    catalog_skills: &BTreeMap<String, CatalogSkill>,
) -> Result<Vec<Skill>, String> {
    let root = install_root(home);
    let mut skills = catalog_skills
        .values()
        .map(|skill| Skill {
            name: skill.name.clone(),
            description: skill.description.clone(),
            status: installation_status(&root.join(&skill.name), Some(&skill.digest)),
        })
        .collect::<Vec<_>>();

    append_removed_skills(&root, catalog_skills, &mut skills)?;
    skills.sort_by(|left, right| left.name.cmp(&right.name));
    Ok(skills)
}

fn state_from_catalog(
    home: &Path,
    catalog_status: CatalogStatus,
    catalog_message: Option<String>,
    catalog_commit: Option<String>,
    checked_at_epoch_seconds: u64,
    auto_update_report: AutoUpdateReport,
    skills: Vec<Skill>,
) -> AppState {
    let root = install_root(home);

    AppState {
        install_root: root.display().to_string(),
        catalog_source: CATALOG_SOURCE,
        catalog_status,
        catalog_message,
        catalog_commit,
        checked_at_epoch_seconds,
        auto_update_report,
        skills,
    }
}

#[cfg(test)]
fn state_at(
    home: &Path,
    catalog: &Path,
    catalog_status: CatalogStatus,
    catalog_message: Option<String>,
    catalog_commit: Option<String>,
    checked_at_epoch_seconds: u64,
    auto_update_report: AutoUpdateReport,
) -> Result<AppState, String> {
    let catalog_skills = catalog_skills(catalog)?;
    let skills = collect_skill_state(home, &catalog_skills)?;
    Ok(state_from_catalog(
        home,
        catalog_status,
        catalog_message,
        catalog_commit,
        checked_at_epoch_seconds,
        auto_update_report,
        skills,
    ))
}

fn archive_skill_path(path: &Path) -> Result<Option<PathBuf>, String> {
    let mut components = Vec::new();

    for component in path.components() {
        let Component::Normal(part) = component else {
            return Err(format!(
                "Archive contains an unsafe path: {}",
                path.display()
            ));
        };
        validate_portable_path_component(part, path)?;
        components.push(part);
    }

    if components.len() < 3 || components[1] != OsStr::new("skills") {
        return Ok(None);
    }

    let skill_name = components[2]
        .to_str()
        .ok_or_else(|| format!("Archive path is not UTF-8: {}", path.display()))?;
    validate_skill_name(skill_name)?;

    let mut relative = PathBuf::from(skill_name);
    for component in &components[3..] {
        relative.push(component);
    }

    Ok(Some(relative))
}

fn extract_catalog_archive(
    bytes: &[u8],
    target: &Path,
) -> Result<BTreeMap<String, CatalogSkill>, String> {
    fs::create_dir_all(target)
        .map_err(|error| format!("Could not create {}: {error}", target.display()))?;
    let decoder = GzDecoder::new(Cursor::new(bytes));
    let mut archive = tar::Archive::new(decoder);
    let entries = archive
        .entries()
        .map_err(|error| format!("Could not read the skillbook archive: {error}"))?;
    let mut portable_paths = BTreeMap::<String, PathBuf>::new();
    let mut extracted_bytes = 0_u64;
    let mut extracted_files = 0_usize;

    for entry in entries {
        let mut entry =
            entry.map_err(|error| format!("Could not read the skillbook archive: {error}"))?;
        let archive_path = entry
            .path()
            .map_err(|error| format!("Archive contains an invalid path: {error}"))?
            .into_owned();
        let Some(relative) = archive_skill_path(&archive_path)? else {
            continue;
        };
        let portable_key = relative
            .components()
            .map(|component| component.as_os_str().to_string_lossy().to_lowercase())
            .collect::<Vec<_>>()
            .join("/");
        if let Some(existing) = portable_paths.get(&portable_key) {
            if existing != &relative {
                return Err(format!(
                    "Archive paths {} and {} collide on Windows",
                    existing.display(),
                    relative.display()
                ));
            }
        } else {
            portable_paths.insert(portable_key, relative.clone());
        }
        let destination = target.join(relative);
        let entry_type = entry.header().entry_type();

        if entry_type.is_dir() {
            fs::create_dir_all(&destination)
                .map_err(|error| format!("Could not create {}: {error}", destination.display()))?;
            continue;
        }
        if !entry_type.is_file() {
            return Err(format!(
                "Archive entry {} is not a regular file or directory",
                archive_path.display()
            ));
        }

        extracted_files += 1;
        if extracted_files > MAX_CATALOG_FILES {
            return Err(format!(
                "The skillbook archive contains more than {MAX_CATALOG_FILES} skill files."
            ));
        }
        extracted_bytes = extracted_bytes
            .checked_add(entry.size())
            .ok_or_else(|| "The skillbook archive is too large.".to_string())?;
        if extracted_bytes > MAX_EXTRACTED_BYTES {
            return Err(format!(
                "The skillbook archive expands beyond {} MB.",
                MAX_EXTRACTED_BYTES / 1024 / 1024
            ));
        }

        let parent = destination
            .parent()
            .ok_or_else(|| format!("{} has no parent", destination.display()))?;
        fs::create_dir_all(parent)
            .map_err(|error| format!("Could not create {}: {error}", parent.display()))?;
        let mut output = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&destination)
            .map_err(|error| format!("Could not create {}: {error}", destination.display()))?;
        std::io::copy(&mut entry, &mut output)
            .map_err(|error| format!("Could not write {}: {error}", destination.display()))?;
        output
            .flush()
            .map_err(|error| format!("Could not write {}: {error}", destination.display()))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;

            let mode = entry.header().mode().map_err(|error| {
                format!(
                    "Could not read {} permissions: {error}",
                    archive_path.display()
                )
            })?;
            fs::set_permissions(&destination, fs::Permissions::from_mode(mode & 0o777)).map_err(
                |error| {
                    format!(
                        "Could not set {} permissions: {error}",
                        destination.display()
                    )
                },
            )?;
        }
    }

    catalog_skills(target)
}

fn temporary_path(parent: &Path, label: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    parent.join(format!(".{label}-{}-{nonce}", std::process::id()))
}

fn activate_catalog(staging: &Path, cache_base: &Path) -> Result<(), String> {
    let current = catalog_dir(cache_base);
    if !current.exists() {
        return fs::rename(staging, &current)
            .map_err(|error| format!("Could not activate the skillbook catalog: {error}"));
    }

    let backup = temporary_path(cache_base, "catalog-previous");
    fs::rename(&current, &backup).map_err(|error| {
        format!("Could not prepare the existing catalog for replacement: {error}")
    })?;

    if let Err(error) = fs::rename(staging, &current) {
        let restore = fs::rename(&backup, &current);
        return match restore {
            Ok(()) => Err(format!("Could not activate the new skillbook catalog: {error}")),
            Err(restore_error) => Err(format!(
                "Could not activate the new skillbook catalog ({error}) or restore the previous catalog ({restore_error})."
            )),
        };
    }

    fs::remove_dir_all(&backup).map_err(|error| {
        format!("The catalog updated, but its previous cache could not be removed: {error}")
    })
}

fn stage_catalog(
    cache_base: &Path,
    bytes: &[u8],
    metadata: &CatalogMetadata,
) -> Result<(PathBuf, BTreeMap<String, CatalogSkill>), String> {
    fs::create_dir_all(cache_base)
        .map_err(|error| format!("Could not create {}: {error}", cache_base.display()))?;
    let staging = temporary_path(cache_base, "catalog-downloading");
    let result = extract_catalog_archive(bytes, &staging).and_then(|skills| {
        write_catalog_metadata(&staging, metadata)?;
        Ok((staging.clone(), skills))
    });

    if result.is_err() && staging.exists() {
        let _ = fs::remove_dir_all(&staging);
    }

    result
}

#[cfg(test)]
fn refresh_catalog(
    cache_base: &Path,
    bytes: &[u8],
    metadata: &CatalogMetadata,
) -> Result<(), String> {
    let (staging, _) = stage_catalog(cache_base, bytes, metadata)?;
    let result = activate_catalog(&staging, cache_base);

    if staging.exists() {
        let _ = fs::remove_dir_all(&staging);
    }

    result
}

fn github_client() -> Result<reqwest::Client, String> {
    reqwest::Client::builder()
        .https_only(true)
        .timeout(Duration::from_secs(30))
        .user_agent(format!("skill-manager/{}", env!("CARGO_PKG_VERSION")))
        .build()
        .map_err(|error| format!("Could not configure the GitHub client: {error}"))
}

async fn check_current_commit(
    client: &reqwest::Client,
    current_metadata: Option<&CatalogMetadata>,
) -> Result<CommitCheck, String> {
    let mut request = client
        .get(CATALOG_REF_URL)
        .header(ACCEPT, "application/vnd.github+json");
    if let Some(etag) = current_metadata.and_then(|metadata| metadata.etag.as_ref()) {
        request = request.header(IF_NONE_MATCH, etag);
    }

    let response = request
        .send()
        .await
        .map_err(|error| format!("Could not check the skillbook commit: {error}"))?;
    if response.status() == StatusCode::NOT_MODIFIED {
        return Ok(CommitCheck::NotModified);
    }
    let response = response
        .error_for_status()
        .map_err(|error| format!("GitHub rejected the skillbook commit check: {error}"))?;

    if response
        .content_length()
        .is_some_and(|length| length > MAX_REF_RESPONSE_BYTES)
    {
        return Err("The GitHub reference response is unexpectedly large.".to_string());
    }

    let etag = response
        .headers()
        .get(ETAG)
        .and_then(|value| value.to_str().ok())
        .map(str::to_string);
    let bytes = response
        .bytes()
        .await
        .map_err(|error| format!("Could not read the skillbook reference response: {error}"))?;
    if bytes.len() as u64 > MAX_REF_RESPONSE_BYTES {
        return Err("The GitHub reference response is unexpectedly large.".to_string());
    }
    let reference = serde_json::from_slice::<GitHubReference>(&bytes)
        .map_err(|error| format!("GitHub returned invalid skillbook commit metadata: {error}"))?;
    if !valid_commit_sha(&reference.object.sha) {
        return Err("GitHub returned an invalid skillbook commit SHA.".to_string());
    }

    Ok(CommitCheck::Current(CatalogMetadata {
        version: CATALOG_METADATA_VERSION,
        source: CATALOG_SOURCE.to_string(),
        commit_sha: reference.object.sha,
        etag,
    }))
}

async fn download_catalog(client: &reqwest::Client, commit_sha: &str) -> Result<Vec<u8>, String> {
    let response = client
        .get(catalog_archive_url(commit_sha)?)
        .send()
        .await
        .map_err(|error| format!("Could not download skillbook: {error}"))?
        .error_for_status()
        .map_err(|error| format!("GitHub rejected the skillbook download: {error}"))?;

    if response
        .content_length()
        .is_some_and(|length| length > MAX_ARCHIVE_BYTES)
    {
        return Err(format!(
            "The skillbook archive exceeds {} MB.",
            MAX_ARCHIVE_BYTES / 1024 / 1024
        ));
    }

    let bytes = response
        .bytes()
        .await
        .map_err(|error| format!("Could not read the skillbook download: {error}"))?;
    if bytes.len() as u64 > MAX_ARCHIVE_BYTES {
        return Err(format!(
            "The skillbook archive exceeds {} MB.",
            MAX_ARCHIVE_BYTES / 1024 / 1024
        ));
    }

    Ok(bytes.to_vec())
}

async fn prepare_catalog_from_github(
    client: &reqwest::Client,
    current_metadata: Option<CatalogMetadata>,
    cache_base: PathBuf,
) -> Result<PreparedCatalog, String> {
    match check_current_commit(client, current_metadata.as_ref()).await? {
        CommitCheck::NotModified => current_metadata
            .map(|metadata| PreparedCatalog::Current(metadata.commit_sha))
            .ok_or_else(|| "GitHub reported an unchanged catalog without a cached commit.".into()),
        CommitCheck::Current(metadata)
            if current_metadata
                .as_ref()
                .is_some_and(|current| current.commit_sha == metadata.commit_sha) =>
        {
            Ok(PreparedCatalog::Current(metadata.commit_sha))
        }
        CommitCheck::Current(metadata) => {
            let bytes = download_catalog(client, &metadata.commit_sha).await?;
            let commit_sha = metadata.commit_sha.clone();
            let (path, skills) = run_blocking("Catalog extraction", move || {
                stage_catalog(&cache_base, &bytes, &metadata)
            })
            .await?;
            Ok(PreparedCatalog::Staged {
                commit_sha,
                path,
                skills,
            })
        }
    }
}

fn copy_directory(source: &Path, target: &Path) -> Result<(), String> {
    fs::create_dir(target)
        .map_err(|error| format!("Could not create {}: {error}", target.display()))?;
    let mut entries = fs::read_dir(source)
        .map_err(|error| format!("Could not read {}: {error}", source.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("Could not read {}: {error}", source.display()))?;
    entries.sort_by_key(fs::DirEntry::file_name);

    for entry in entries {
        let source_path = entry.path();
        let destination = target.join(entry.file_name());
        let file_type = entry
            .file_type()
            .map_err(|error| format!("Could not inspect {}: {error}", source_path.display()))?;

        if file_type.is_dir() {
            copy_directory(&source_path, &destination)?;
        } else if file_type.is_file() {
            fs::copy(&source_path, &destination).map_err(|error| {
                format!(
                    "Could not copy {} to {}: {error}",
                    source_path.display(),
                    destination.display()
                )
            })?;
        } else {
            return Err(format!(
                "{} is not a regular file or directory",
                source_path.display()
            ));
        }
    }

    Ok(())
}

fn write_install_marker(target: &Path, digest: &str) -> Result<(), String> {
    let marker = InstallMarker {
        version: MARKER_VERSION,
        source: CATALOG_SOURCE.to_string(),
        skill_digest: digest.to_string(),
    };
    let mut contents = serde_json::to_string_pretty(&marker)
        .map_err(|error| format!("Could not create the ownership marker: {error}"))?;
    contents.push('\n');
    fs::write(target.join(MARKER_FILE), contents)
        .map_err(|error| format!("Could not write the ownership marker: {error}"))
}

fn catalog_skill_at(catalog: &Path, name: &str) -> Result<CatalogSkill, String> {
    validate_skill_name(name)?;
    let source = catalog.join(name);
    if !source.is_dir() {
        return Err(format!("Unknown skill: {name}"));
    }
    if source.join(MARKER_FILE).exists() {
        return Err(format!(
            "{} contains the reserved marker file",
            source.display()
        ));
    }

    let (declared_name, description) = skill_frontmatter(&source)?;
    if declared_name != name {
        return Err(format!("{name} has invalid catalog metadata."));
    }
    let digest = directory_digest(&source)?;
    Ok(CatalogSkill {
        name: name.to_string(),
        description,
        digest,
    })
}

fn replace_skill_at(home: &Path, catalog: &Path, skill: &CatalogSkill) -> Result<(), String> {
    let name = &skill.name;
    let source = catalog.join(name);
    let root = install_root(home);
    let target = root.join(name);

    fs::create_dir_all(&root)
        .map_err(|error| format!("Could not create {}: {error}", root.display()))?;
    let staging = temporary_path(&root, &format!("{name}-installing"));
    let result = (|| {
        copy_directory(&source, &staging)?;
        write_install_marker(&staging, &skill.digest)?;

        if !target.exists() {
            return fs::rename(&staging, &target)
                .map_err(|error| format!("Could not finish installing {name}: {error}"));
        }

        let backup = temporary_path(&root, &format!("{name}-previous"));
        fs::rename(&target, &backup)
            .map_err(|error| format!("Could not prepare {name} for update: {error}"))?;
        if let Err(error) = fs::rename(&staging, &target) {
            let restore = fs::rename(&backup, &target);
            return match restore {
                Ok(()) => Err(format!("Could not finish updating {name}: {error}")),
                Err(restore_error) => Err(format!(
                    "Could not finish updating {name} ({error}) or restore the installed copy ({restore_error})."
                )),
            };
        }
        fs::remove_dir_all(&backup).map_err(|error| {
            format!("{name} updated, but its previous copy could not be removed: {error}")
        })
    })();

    if staging.exists() {
        let _ = fs::remove_dir_all(&staging);
    }

    result
}

fn next_backup_path(home: &Path, name: &str) -> Result<PathBuf, String> {
    let parent = backup_root(home).join(name);
    fs::create_dir_all(&parent)
        .map_err(|error| format!("Could not create {}: {error}", parent.display()))?;
    let timestamp = current_epoch_seconds();

    for suffix in 0..10_000_u16 {
        let directory_name = if suffix == 0 {
            timestamp.to_string()
        } else {
            format!("{timestamp}-{suffix}")
        };
        let candidate = parent.join(directory_name);
        if !path_entry_exists(&candidate) {
            return Ok(candidate);
        }
    }

    Err(format!(
        "Could not choose a unique backup path in {}.",
        parent.display()
    ))
}

fn activate_unmanaged_replacement(
    name: &str,
    target: &Path,
    staging: &Path,
    backup: &Path,
) -> Result<(), String> {
    fs::rename(target, backup)
        .map_err(|error| format!("Could not back up the existing {name} skill: {error}"))?;

    if let Err(error) = fs::rename(staging, target) {
        let restore = fs::rename(backup, target);
        return match restore {
            Ok(()) => Err(format!(
                "Could not finish replacing {name}; the original skill was restored: {error}"
            )),
            Err(restore_error) => Err(format!(
                "Could not finish replacing {name} ({error}) or restore the original skill ({restore_error}). Its backup remains at {}.",
                backup.display()
            )),
        };
    }

    Ok(())
}

fn adopt_at(home: &Path, catalog: &Path, name: &str) -> Result<(), String> {
    let skill = catalog_skill_at(catalog, name)?;
    let target = install_root(home).join(name);

    if !path_entry_exists(&target) {
        return Err(format!("{name} no longer exists at {}.", target.display()));
    }
    if !matches!(install_ownership(&target), InstallOwnership::Unmanaged) {
        return Err(format!(
            "{} is already managed by Skill Manager.",
            target.display()
        ));
    }
    if unmanaged_status(&target, Some(&skill.digest)) != SkillStatus::UnmanagedMatch {
        return Err(format!(
            "{} does not exactly match the skillbook copy. It was not adopted.",
            target.display()
        ));
    }

    write_install_marker(&target, &skill.digest)
}

fn replace_unmanaged_at(
    home: &Path,
    catalog: &Path,
    name: &str,
) -> Result<ReplaceUnmanagedResult, String> {
    let skill = catalog_skill_at(catalog, name)?;
    let root = install_root(home);
    let target = root.join(name);

    if !path_entry_exists(&target) {
        return Err(format!("{name} no longer exists at {}.", target.display()));
    }
    if !matches!(install_ownership(&target), InstallOwnership::Unmanaged) {
        return Err(format!(
            "{} is managed by Skill Manager and cannot be replaced as an unmanaged conflict.",
            target.display()
        ));
    }
    if unmanaged_status(&target, Some(&skill.digest)) == SkillStatus::UnmanagedMatch {
        return Err(format!(
            "{} exactly matches skillbook. Use Manage instead of Replace.",
            target.display()
        ));
    }

    fs::create_dir_all(&root)
        .map_err(|error| format!("Could not create {}: {error}", root.display()))?;
    let staging = temporary_path(&root, &format!("{name}-installing"));
    let result = (|| {
        copy_directory(&catalog.join(name), &staging)?;
        write_install_marker(&staging, &skill.digest)?;

        if !path_entry_exists(&target) {
            return Err(format!(
                "{name} disappeared before it could be backed up. Nothing was installed."
            ));
        }
        if !matches!(install_ownership(&target), InstallOwnership::Unmanaged) {
            return Err(format!(
                "{} became managed before it could be replaced. Nothing was changed.",
                target.display()
            ));
        }

        let backup = next_backup_path(home, name)?;
        activate_unmanaged_replacement(name, &target, &staging, &backup)?;
        Ok(ReplaceUnmanagedResult {
            backup_path: backup.display().to_string(),
        })
    })();

    if path_entry_exists(&staging) {
        let _ = fs::remove_dir_all(&staging);
    }

    result
}

fn install_catalog_skill_at(
    home: &Path,
    catalog: &Path,
    skill: &CatalogSkill,
) -> Result<(), String> {
    let target = install_root(home).join(&skill.name);

    if path_entry_exists(&target) {
        match installation_status(&target, Some(&skill.digest)) {
            SkillStatus::Installed => {
                return Err(format!("{} is already installed.", skill.name));
            }
            SkillStatus::UpdateAvailable => {}
            SkillStatus::Modified => {
                return Err(format!(
                    "{} contains local changes. Skill Manager will not overwrite it.",
                    target.display()
                ));
            }
            SkillStatus::Available
            | SkillStatus::Removed
            | SkillStatus::UnmanagedMatch
            | SkillStatus::Conflict => {
                return Err(format!(
                    "{} already exists. Skill Manager will not overwrite it.",
                    target.display()
                ));
            }
        }
    }

    replace_skill_at(home, catalog, skill)
}

fn install_at(home: &Path, catalog: &Path, name: &str) -> Result<(), String> {
    let skill = catalog_skill_at(catalog, name)?;
    install_catalog_skill_at(home, catalog, &skill)
}

fn reconcile_skill_state(
    home: &Path,
    catalog: &Path,
    catalog_skills: &BTreeMap<String, CatalogSkill>,
) -> Result<(AutoUpdateReport, Vec<Skill>), String> {
    let root = install_root(home);
    let mut report = AutoUpdateReport::default();
    let mut visible_skills = Vec::with_capacity(catalog_skills.len());

    for skill in catalog_skills.values() {
        let target = root.join(&skill.name);
        if !path_entry_exists(&target) {
            visible_skills.push(Skill {
                name: skill.name.clone(),
                description: skill.description.clone(),
                status: SkillStatus::Available,
            });
            continue;
        }

        let status = match install_ownership(&target) {
            InstallOwnership::Unmanaged => unmanaged_status(&target, Some(&skill.digest)),
            InstallOwnership::Legacy => {
                report.skipped_legacy_skills.push(skill.name.clone());
                SkillStatus::UpdateAvailable
            }
            InstallOwnership::Managed(marker) => {
                let installed_digest = match directory_digest(&target) {
                    Ok(digest) => digest,
                    Err(message) => {
                        report.failed_skills.push(SkillUpdateFailure {
                            name: skill.name.clone(),
                            message,
                        });
                        visible_skills.push(Skill {
                            name: skill.name.clone(),
                            description: skill.description.clone(),
                            status: SkillStatus::Modified,
                        });
                        continue;
                    }
                };

                if installed_digest != marker.skill_digest {
                    report.skipped_modified_skills.push(skill.name.clone());
                    SkillStatus::Modified
                } else if installed_digest == skill.digest {
                    SkillStatus::Installed
                } else {
                    match replace_skill_at(home, catalog, skill) {
                        Ok(()) => {
                            report.updated_skills.push(skill.name.clone());
                            SkillStatus::Installed
                        }
                        Err(message) => {
                            report.failed_skills.push(SkillUpdateFailure {
                                name: skill.name.clone(),
                                message,
                            });
                            SkillStatus::UpdateAvailable
                        }
                    }
                }
            }
        };

        visible_skills.push(Skill {
            name: skill.name.clone(),
            description: skill.description.clone(),
            status,
        });
    }

    append_removed_skills(&root, catalog_skills, &mut visible_skills)?;
    visible_skills.sort_by(|left, right| left.name.cmp(&right.name));
    Ok((report, visible_skills))
}

#[cfg(test)]
fn auto_update_at(home: &Path, catalog: &Path) -> Result<AutoUpdateReport, String> {
    let skills = catalog_skills(catalog)?;
    reconcile_skill_state(home, catalog, &skills).map(|(report, _)| report)
}

fn uninstall_at(home: &Path, name: &str) -> Result<(), String> {
    validate_skill_name(name)?;
    let target = install_root(home).join(name);

    if !path_entry_exists(&target) {
        return Err(format!("{name} is not installed."));
    }

    match install_ownership(&target) {
        InstallOwnership::Unmanaged => {
            return Err(format!(
                "{} is not managed by Skill Manager. It was not removed.",
                target.display()
            ));
        }
        InstallOwnership::Legacy => {}
        InstallOwnership::Managed(marker) => {
            let digest = directory_digest(&target)?;
            if digest != marker.skill_digest {
                return Err(format!(
                    "{} contains local changes. It was not removed.",
                    target.display()
                ));
            }
        }
    }

    fs::remove_dir_all(&target).map_err(|error| format!("Could not uninstall {name}: {error}"))
}

fn reconciled_app_state(
    home: &Path,
    catalog: &Path,
    catalog_skills: &BTreeMap<String, CatalogSkill>,
    catalog_status: CatalogStatus,
    catalog_message: Option<String>,
    catalog_commit: Option<String>,
) -> Result<AppState, String> {
    let (auto_update_report, skills) = reconcile_skill_state(home, catalog, catalog_skills)?;
    Ok(state_from_catalog(
        home,
        catalog_status,
        catalog_message,
        catalog_commit,
        current_epoch_seconds(),
        auto_update_report,
        skills,
    ))
}

fn reconciled_app_state_from_disk(
    home: &Path,
    catalog: &Path,
    catalog_status: CatalogStatus,
    catalog_message: Option<String>,
    catalog_commit: Option<String>,
) -> Result<AppState, String> {
    let skills = catalog_skills(catalog)?;
    reconciled_app_state(
        home,
        catalog,
        &skills,
        catalog_status,
        catalog_message,
        catalog_commit,
    )
}

fn cached_state_after_error(
    home: &Path,
    cache_base: &Path,
    error: String,
) -> Result<AppState, String> {
    let catalog = catalog_dir(cache_base);
    if !catalog.is_dir() {
        return Err(format!(
            "Could not load the skillbook catalog and no cached copy is available. {error}"
        ));
    }

    let commit = read_catalog_metadata(&catalog).map(|metadata| metadata.commit_sha);
    reconciled_app_state_from_disk(
        home,
        &catalog,
        CatalogStatus::Cached,
        Some(format!(
            "Could not refresh from GitHub. Using the last downloaded catalog. {error}"
        )),
        commit,
    )
}

#[tauri::command]
async fn load_cached_app_state(
    runtime: State<'_, RuntimeState>,
) -> Result<Option<AppState>, String> {
    let _guard = runtime.catalog_lock.lock().await;
    let home = home_dir()?;
    let cache_base = cache_base_dir()?;
    run_blocking("Cached catalog load", move || {
        let catalog = catalog_dir(&cache_base);
        if !catalog.is_dir() {
            return Ok(None);
        }

        let commit = read_catalog_metadata(&catalog).map(|metadata| metadata.commit_sha);
        let catalog_skills = catalog_skills(&catalog)?;
        let skills = collect_skill_state(&home, &catalog_skills)?;
        Ok(Some(state_from_catalog(
            &home,
            CatalogStatus::Cached,
            None,
            commit,
            current_epoch_seconds(),
            AutoUpdateReport::default(),
            skills,
        )))
    })
    .await
}

#[tauri::command]
async fn sync_app_state(runtime: State<'_, RuntimeState>) -> Result<AppState, String> {
    let _sync_guard = runtime.sync_lock.lock().await;
    let home = home_dir()?;
    let cache_base = cache_base_dir()?;
    let catalog = catalog_dir(&cache_base);
    let current_metadata = {
        let _catalog_guard = runtime.catalog_lock.lock().await;
        run_blocking("Catalog metadata load", move || {
            Ok(read_catalog_metadata(&catalog))
        })
        .await?
    };
    let prepared =
        prepare_catalog_from_github(&runtime.github_client, current_metadata, cache_base.clone())
            .await;
    let _catalog_guard = runtime.catalog_lock.lock().await;

    match prepared {
        Ok(PreparedCatalog::Current(commit_sha)) => {
            let catalog = catalog_dir(&cache_base);
            run_blocking("Catalog reconciliation", move || {
                reconciled_app_state_from_disk(
                    &home,
                    &catalog,
                    CatalogStatus::Fresh,
                    None,
                    Some(commit_sha),
                )
            })
            .await
        }
        Ok(PreparedCatalog::Staged {
            commit_sha,
            path,
            skills,
        }) => {
            run_blocking("Catalog activation", move || {
                let activation = activate_catalog(&path, &cache_base);
                if path.exists() {
                    let _ = fs::remove_dir_all(&path);
                }

                match activation {
                    Ok(()) => reconciled_app_state(
                        &home,
                        &catalog_dir(&cache_base),
                        &skills,
                        CatalogStatus::Fresh,
                        None,
                        Some(commit_sha),
                    ),
                    Err(error) => cached_state_after_error(&home, &cache_base, error),
                }
            })
            .await
        }
        Err(error) => {
            run_blocking("Cached catalog reconciliation", move || {
                cached_state_after_error(&home, &cache_base, error)
            })
            .await
        }
    }
}

#[tauri::command]
async fn install_skill(runtime: State<'_, RuntimeState>, name: &str) -> Result<(), String> {
    let _guard = runtime.catalog_lock.lock().await;
    let home = home_dir()?;
    let catalog = catalog_dir(&cache_base_dir()?);
    let name = name.to_string();
    run_blocking("Skill installation", move || {
        install_at(&home, &catalog, &name)
    })
    .await
}

#[tauri::command]
async fn adopt_skill(runtime: State<'_, RuntimeState>, name: &str) -> Result<(), String> {
    let _guard = runtime.catalog_lock.lock().await;
    let home = home_dir()?;
    let catalog = catalog_dir(&cache_base_dir()?);
    let name = name.to_string();
    run_blocking("Skill adoption", move || adopt_at(&home, &catalog, &name)).await
}

#[tauri::command]
async fn replace_unmanaged_skill(
    runtime: State<'_, RuntimeState>,
    name: &str,
) -> Result<ReplaceUnmanagedResult, String> {
    let _guard = runtime.catalog_lock.lock().await;
    let home = home_dir()?;
    let catalog = catalog_dir(&cache_base_dir()?);
    let name = name.to_string();
    run_blocking("Unmanaged skill replacement", move || {
        replace_unmanaged_at(&home, &catalog, &name)
    })
    .await
}

#[tauri::command]
async fn uninstall_skill(runtime: State<'_, RuntimeState>, name: &str) -> Result<(), String> {
    let _guard = runtime.catalog_lock.lock().await;
    let home = home_dir()?;
    let name = name.to_string();
    run_blocking("Skill removal", move || uninstall_at(&home, &name)).await
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let runtime_state =
        RuntimeState::new().expect("could not initialize the Skill Manager runtime");
    tauri::Builder::default()
        .manage(runtime_state)
        .invoke_handler(tauri::generate_handler![
            load_cached_app_state,
            sync_app_state,
            install_skill,
            adopt_skill,
            replace_unmanaged_skill,
            uninstall_skill
        ])
        .run(tauri::generate_context!())
        .expect("error while running Tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;
    use flate2::{write::GzEncoder, Compression};
    use tar::{Builder, Header};

    const TEST_COMMIT_SHA: &str = "0123456789abcdef0123456789abcdef01234567";

    fn write_skill(catalog: &Path, name: &str, description: &str) {
        let skill = catalog.join(name);
        fs::create_dir_all(&skill).expect("skill directory");
        fs::write(
            skill.join("SKILL.md"),
            format!("---\nname: {name}\ndescription: \"{description}\"\n---\n\n# {name}\n"),
        )
        .expect("skill contents");
    }

    fn test_state(home: &Path, catalog: &Path) -> AppState {
        state_at(
            home,
            catalog,
            CatalogStatus::Fresh,
            None,
            None,
            0,
            AutoUpdateReport::default(),
        )
        .expect("state should load")
    }

    fn test_archive() -> Vec<u8> {
        let encoder = GzEncoder::new(Vec::new(), Compression::default());
        let mut builder = Builder::new(encoder);
        let contents =
            b"---\nname: remote-skill\ndescription: \"Downloaded skill\"\n---\n\n# Remote\n";
        let mut header = Header::new_gnu();
        header.set_size(contents.len() as u64);
        header.set_mode(0o644);
        header.set_cksum();
        builder
            .append_data(
                &mut header,
                "skillbook-main/skills/remote-skill/SKILL.md",
                &contents[..],
            )
            .expect("archive entry");
        builder
            .into_inner()
            .expect("archive")
            .finish()
            .expect("compressed archive")
    }

    #[test]
    fn accepts_windows_utf8_frontmatter_and_legacy_marker() {
        let catalog = tempfile::tempdir().expect("temporary catalog");
        let skill = catalog.path().join("hello-world");
        fs::create_dir_all(&skill).expect("skill directory");
        fs::write(
            skill.join("SKILL.md"),
            "\u{feff}---\r\nname: hello-world\r\ndescription: \"Résumé checks\"\r\n---\r\n",
        )
        .expect("skill contents");
        fs::write(
            skill.join(MARKER_FILE),
            "\u{feff}Managed by Skill Manager. Do not edit this file.\r\n",
        )
        .expect("legacy marker");

        assert_eq!(
            skill_frontmatter(&skill).expect("frontmatter"),
            ("hello-world".to_string(), "Résumé checks".to_string())
        );
        assert!(matches!(
            install_ownership(&skill),
            InstallOwnership::Legacy
        ));
    }

    #[test]
    fn rejects_non_utf8_skill_metadata() {
        let catalog = tempfile::tempdir().expect("temporary catalog");
        let skill = catalog.path().join("hello-world");
        fs::create_dir_all(&skill).expect("skill directory");
        fs::write(skill.join("SKILL.md"), [0xff]).expect("invalid skill contents");

        let error = skill_frontmatter(&skill).expect_err("invalid UTF-8 should be rejected");

        assert!(error.contains("must be valid UTF-8"));
    }

    #[test]
    fn rejects_paths_that_cannot_be_created_on_windows() {
        assert!(validate_skill_name("con").is_err());
        assert!(validate_skill_name("com1").is_err());
        assert!(validate_portable_path_component(
            OsStr::new("NUL.txt"),
            Path::new("skillbook-main/skills/hello-world/NUL.txt")
        )
        .is_err());
        assert!(validate_portable_path_component(
            OsStr::new("trailing."),
            Path::new("skillbook-main/skills/hello-world/trailing.")
        )
        .is_err());
        assert!(validate_portable_path_component(
            OsStr::new("colon:name"),
            Path::new("skillbook-main/skills/hello-world/colon:name")
        )
        .is_err());
    }

    #[test]
    fn detects_case_insensitive_archive_collisions() {
        let encoder = GzEncoder::new(Vec::new(), Compression::default());
        let mut builder = Builder::new(encoder);
        for path in [
            "skillbook-main/skills/remote-skill/SKILL.md",
            "skillbook-main/skills/remote-skill/skill.md",
        ] {
            let contents = b"---\nname: remote-skill\ndescription: \"Downloaded skill\"\n---\n";
            let mut header = Header::new_gnu();
            header.set_size(contents.len() as u64);
            header.set_mode(0o644);
            header.set_cksum();
            builder
                .append_data(&mut header, path, &contents[..])
                .expect("archive entry");
        }
        let bytes = builder
            .into_inner()
            .expect("archive")
            .finish()
            .expect("compressed archive");
        let target = tempfile::tempdir().expect("temporary extraction");

        let error =
            extract_catalog_archive(&bytes, target.path()).expect_err("collision should fail");

        assert!(error.contains("collide on Windows"));
    }

    #[test]
    fn catalog_reads_skills_from_a_directory() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "python-standards", "Strict Python");
        write_skill(catalog.path(), "git-ops", "Safe Git");

        let state = test_state(home.path(), catalog.path());

        assert_eq!(state.skills.len(), 2);
        assert_eq!(state.skills[0].name, "git-ops");
        assert_eq!(state.skills[1].name, "python-standards");
        assert!(state
            .skills
            .iter()
            .all(|skill| skill.status == SkillStatus::Available));
    }

    #[test]
    fn install_and_uninstall_round_trip() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Test skill");
        let target = install_root(home.path()).join("hello-world");

        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");

        assert!(target.join("SKILL.md").is_file());
        assert!(target.join(MARKER_FILE).is_file());
        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Installed
        );

        uninstall_at(home.path(), "hello-world").expect("uninstall should work");
        assert!(!target.exists());
    }

    #[test]
    fn identical_unmanaged_skill_can_be_adopted() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Test skill");
        let target = install_root(home.path()).join("hello-world");
        fs::create_dir_all(&target).expect("unmanaged directory");
        fs::copy(
            catalog.path().join("hello-world/SKILL.md"),
            target.join("SKILL.md"),
        )
        .expect("matching unmanaged skill");

        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::UnmanagedMatch
        );
        let report =
            auto_update_at(home.path(), catalog.path()).expect("automatic update should finish");
        assert!(report.updated_skills.is_empty());
        assert!(!target.join(MARKER_FILE).exists());
        assert!(replace_unmanaged_at(home.path(), catalog.path(), "hello-world").is_err());
        assert!(!backup_root(home.path()).exists());

        adopt_at(home.path(), catalog.path(), "hello-world").expect("adoption should work");

        assert!(target.join(MARKER_FILE).is_file());
        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Installed
        );
    }

    #[test]
    fn adoption_refuses_a_different_unmanaged_skill() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Catalog version");
        let target = install_root(home.path()).join("hello-world");
        fs::create_dir_all(&target).expect("unmanaged directory");
        fs::write(target.join("SKILL.md"), "local version").expect("unmanaged skill");

        let error =
            adopt_at(home.path(), catalog.path(), "hello-world").expect_err("adoption should fail");

        assert!(error.contains("does not exactly match"));
        assert_eq!(
            fs::read_to_string(target.join("SKILL.md")).expect("unmanaged skill remains"),
            "local version"
        );
        assert!(!target.join(MARKER_FILE).exists());
    }

    #[test]
    fn replacement_backs_up_a_different_unmanaged_skill() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Catalog version");
        let target = install_root(home.path()).join("hello-world");
        fs::create_dir_all(&target).expect("unmanaged directory");
        fs::write(target.join("SKILL.md"), "local version").expect("unmanaged skill");
        fs::write(target.join("local-notes.md"), "keep me").expect("local notes");

        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Conflict
        );
        let report =
            auto_update_at(home.path(), catalog.path()).expect("automatic update should finish");
        assert!(report.updated_skills.is_empty());
        assert_eq!(
            fs::read_to_string(target.join("SKILL.md")).expect("unmanaged skill remains"),
            "local version"
        );

        let replacement = replace_unmanaged_at(home.path(), catalog.path(), "hello-world")
            .expect("replacement should work");
        let backup = PathBuf::from(replacement.backup_path);

        assert!(backup.starts_with(backup_root(home.path()).join("hello-world")));
        assert_eq!(
            fs::read_to_string(backup.join("SKILL.md")).expect("backed-up skill"),
            "local version"
        );
        assert_eq!(
            fs::read_to_string(backup.join("local-notes.md")).expect("backed-up notes"),
            "keep me"
        );
        assert!(target.join(MARKER_FILE).is_file());
        assert!(fs::read_to_string(target.join("SKILL.md"))
            .expect("catalog skill")
            .contains("Catalog version"));
        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Installed
        );
    }

    #[test]
    fn failed_replacement_restores_the_original_skill() {
        let home = tempfile::tempdir().expect("temporary home");
        let target = install_root(home.path()).join("hello-world");
        let backup = backup_root(home.path()).join("hello-world/123");
        let missing_staging = install_root(home.path()).join(".missing-staging");
        fs::create_dir_all(&target).expect("unmanaged directory");
        fs::create_dir_all(backup.parent().expect("backup parent")).expect("backup root");
        fs::write(target.join("SKILL.md"), "local version").expect("unmanaged skill");

        let error =
            activate_unmanaged_replacement("hello-world", &target, &missing_staging, &backup)
                .expect_err("activation should fail");

        assert!(error.contains("original skill was restored"));
        assert_eq!(
            fs::read_to_string(target.join("SKILL.md")).expect("restored skill"),
            "local version"
        );
        assert!(!backup.exists());
    }

    #[test]
    fn update_replaces_an_unmodified_managed_skill() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Version one");
        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");
        write_skill(catalog.path(), "hello-world", "Version two");

        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::UpdateAvailable
        );

        install_at(home.path(), catalog.path(), "hello-world").expect("update should work");
        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Installed
        );
        assert!(
            fs::read_to_string(install_root(home.path()).join("hello-world/SKILL.md"))
                .expect("installed skill")
                .contains("Version two")
        );
    }

    #[test]
    fn auto_update_updates_only_installed_unmodified_skills() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Version one");
        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");
        write_skill(catalog.path(), "hello-world", "Version two");
        write_skill(catalog.path(), "not-installed", "Leave uninstalled");

        let report =
            auto_update_at(home.path(), catalog.path()).expect("automatic update should work");

        assert_eq!(report.updated_skills, ["hello-world"]);
        assert!(report.failed_skills.is_empty());
        assert!(!install_root(home.path()).join("not-installed").exists());
        assert!(
            fs::read_to_string(install_root(home.path()).join("hello-world/SKILL.md"))
                .expect("installed skill")
                .contains("Version two")
        );
    }

    #[test]
    fn modified_install_is_not_overwritten_or_removed() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Test skill");
        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");
        let installed = install_root(home.path()).join("hello-world/SKILL.md");
        fs::write(&installed, "local changes").expect("local edit");

        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Modified
        );
        let report =
            auto_update_at(home.path(), catalog.path()).expect("automatic update should finish");
        assert_eq!(report.skipped_modified_skills, ["hello-world"]);
        assert!(install_at(home.path(), catalog.path(), "hello-world").is_err());
        assert!(adopt_at(home.path(), catalog.path(), "hello-world").is_err());
        assert!(replace_unmanaged_at(home.path(), catalog.path(), "hello-world").is_err());
        assert!(uninstall_at(home.path(), "hello-world").is_err());
        assert_eq!(
            fs::read_to_string(installed).expect("local edit remains"),
            "local changes"
        );
    }

    #[test]
    fn automatic_update_skips_legacy_install_markers() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Catalog version");
        let target = install_root(home.path()).join("hello-world");
        fs::create_dir_all(&target).expect("installed directory");
        fs::write(
            target.join("SKILL.md"),
            "---\nname: hello-world\ndescription: \"Legacy version\"\n---\n",
        )
        .expect("legacy skill");
        fs::write(target.join(MARKER_FILE), LEGACY_MARKER_CONTENTS).expect("legacy marker");

        let report =
            auto_update_at(home.path(), catalog.path()).expect("automatic update should finish");

        assert_eq!(report.skipped_legacy_skills, ["hello-world"]);
        assert!(fs::read_to_string(target.join("SKILL.md"))
            .expect("legacy skill remains")
            .contains("Legacy version"));
    }

    #[test]
    fn removed_managed_skill_remains_available_for_uninstall() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Test skill");
        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");
        fs::remove_dir_all(catalog.path().join("hello-world")).expect("remove from catalog");
        write_skill(catalog.path(), "other-skill", "Keeps catalog valid");

        let state = test_state(home.path(), catalog.path());
        let removed = state
            .skills
            .iter()
            .find(|skill| skill.name == "hello-world")
            .expect("removed skill remains visible");

        assert_eq!(removed.status, SkillStatus::Removed);
        let report =
            auto_update_at(home.path(), catalog.path()).expect("automatic update should finish");
        assert!(report.updated_skills.is_empty());
        assert!(install_root(home.path()).join("hello-world").exists());
        uninstall_at(home.path(), "hello-world").expect("removed skill can be uninstalled");
    }

    #[test]
    fn extracts_and_validates_a_skillbook_archive() {
        let target = tempfile::tempdir().expect("temporary extraction");

        extract_catalog_archive(&test_archive(), target.path()).expect("archive should extract");

        let skills = catalog_skills(target.path()).expect("catalog should validate");
        assert!(skills.contains_key("remote-skill"));
    }

    #[test]
    fn refreshed_catalog_records_its_commit_metadata() {
        let cache = tempfile::tempdir().expect("temporary cache");
        let metadata = CatalogMetadata {
            version: CATALOG_METADATA_VERSION,
            source: CATALOG_SOURCE.to_string(),
            commit_sha: TEST_COMMIT_SHA.to_string(),
            etag: Some("\"catalog-etag\"".to_string()),
        };

        refresh_catalog(cache.path(), &test_archive(), &metadata)
            .expect("catalog refresh should work");

        let stored = read_catalog_metadata(&catalog_dir(cache.path()))
            .expect("catalog metadata should be readable");
        assert_eq!(stored.commit_sha, TEST_COMMIT_SHA);
        assert_eq!(stored.etag.as_deref(), Some("\"catalog-etag\""));
    }

    #[test]
    fn archive_urls_require_a_full_lowercase_commit_sha() {
        assert_eq!(
            catalog_archive_url(TEST_COMMIT_SHA).expect("valid commit"),
            format!("{CATALOG_SOURCE}/archive/{TEST_COMMIT_SHA}.tar.gz")
        );
        assert!(catalog_archive_url("main").is_err());
        assert!(catalog_archive_url("0123456789ABCDEF0123456789ABCDEF01234567").is_err());
    }

    #[test]
    fn uninstall_refuses_an_unmanaged_directory() {
        let home = tempfile::tempdir().expect("temporary home");
        let target = install_root(home.path()).join("hello-world");
        fs::create_dir_all(&target).expect("unmanaged directory");
        fs::write(target.join("SKILL.md"), "keep me").expect("unmanaged skill");

        let error =
            uninstall_at(home.path(), "hello-world").expect_err("uninstall should be refused");

        assert!(error.contains("not managed"));
        assert!(target.join("SKILL.md").is_file());
    }
}
