use flate2::read::GzDecoder;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::ffi::OsStr;
use std::fs::{self, File, OpenOptions};
use std::io::{Cursor, Read, Write};
use std::path::{Component, Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tauri::{async_runtime::Mutex, State};

const CATALOG_SOURCE: &str = "https://github.com/jacobragsdale/skillbook";
const CATALOG_ARCHIVE_URL: &str =
    "https://github.com/jacobragsdale/skillbook/archive/refs/heads/main.tar.gz";
const MAX_ARCHIVE_BYTES: u64 = 25 * 1024 * 1024;
const MAX_EXTRACTED_BYTES: u64 = 50 * 1024 * 1024;
const MAX_CATALOG_FILES: usize = 2_000;
const MARKER_FILE: &str = ".skill-manager-managed";
const LEGACY_MARKER_CONTENTS: &str = "Managed by Skill Manager. Do not edit this file.\n";
const MARKER_VERSION: u8 = 1;

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct Skill {
    name: String,
    description: String,
    status: SkillStatus,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
enum SkillStatus {
    Available,
    Installed,
    UpdateAvailable,
    Removed,
    Modified,
    Conflict,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum CatalogStatus {
    Fresh,
    Cached,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct AppState {
    install_root: String,
    catalog_source: &'static str,
    catalog_status: CatalogStatus,
    catalog_message: Option<String>,
    skills: Vec<Skill>,
}

#[derive(Debug)]
struct CatalogSkill {
    name: String,
    description: String,
    digest: String,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
struct InstallMarker {
    version: u8,
    source: String,
    skill_digest: String,
}

enum InstallOwnership {
    Unmanaged,
    Legacy,
    Managed(InstallMarker),
}

#[derive(Default)]
struct RuntimeState {
    catalog_lock: Mutex<()>,
}

fn home_dir() -> Result<PathBuf, String> {
    dirs::home_dir().ok_or_else(|| "Could not find your home directory.".to_string())
}

fn cache_base_dir() -> Result<PathBuf, String> {
    dirs::cache_dir()
        .map(|directory| directory.join("skill-manager"))
        .ok_or_else(|| "Could not find your cache directory.".to_string())
}

fn catalog_dir(cache_base: &Path) -> PathBuf {
    cache_base.join("catalog")
}

fn install_root(home: &Path) -> PathBuf {
    home.join(".agents").join("skills")
}

fn validate_skill_name(name: &str) -> Result<(), String> {
    let valid = !name.is_empty()
        && name
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
        && !name.starts_with('-')
        && !name.ends_with('-')
        && !name.contains("--");

    if valid {
        Ok(())
    } else {
        Err(format!("Invalid skill name: {name}"))
    }
}

fn frontmatter_value(contents: &str, key: &str) -> Option<String> {
    let normalized = contents.replace("\r\n", "\n");
    let frontmatter = normalized.strip_prefix("---\n")?.split_once("\n---")?.0;
    let prefix = format!("{key}:");

    frontmatter.lines().find_map(|line| {
        line.strip_prefix(&prefix)
            .map(str::trim)
            .map(|value| value.trim_matches(['"', '\'']).to_string())
            .filter(|value| !value.is_empty())
    })
}

fn skill_frontmatter(skill: &Path) -> Result<(String, String), String> {
    let path = skill.join("SKILL.md");
    let contents = fs::read_to_string(&path)
        .map_err(|error| format!("Could not read {}: {error}", path.display()))?;
    let name = frontmatter_value(&contents, "name")
        .ok_or_else(|| format!("{} is missing a name", path.display()))?;
    let description = frontmatter_value(&contents, "description")
        .ok_or_else(|| format!("{} is missing a description", path.display()))?;

    Ok((name, description))
}

fn relative_path(root: &Path, path: &Path) -> Result<String, String> {
    let relative = path
        .strip_prefix(root)
        .map_err(|_| format!("{} is outside {}", path.display(), root.display()))?;
    let mut parts = Vec::new();

    for component in relative.components() {
        let Component::Normal(part) = component else {
            return Err(format!("{} has an invalid path", path.display()));
        };
        parts.push(
            part.to_str()
                .ok_or_else(|| format!("{} is not UTF-8", path.display()))?,
        );
    }

    Ok(parts.join("/"))
}

fn update_hash_field(hasher: &mut Sha256, value: &[u8]) {
    hasher.update((value.len() as u64).to_le_bytes());
    hasher.update(value);
}

fn hash_directory_entries(root: &Path, current: &Path, hasher: &mut Sha256) -> Result<(), String> {
    let mut entries = fs::read_dir(current)
        .map_err(|error| format!("Could not read {}: {error}", current.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("Could not read {}: {error}", current.display()))?;
    entries.sort_by_key(fs::DirEntry::file_name);

    for entry in entries {
        if current == root && entry.file_name() == OsStr::new(MARKER_FILE) {
            continue;
        }

        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|error| format!("Could not inspect {}: {error}", path.display()))?;
        let relative = relative_path(root, &path)?;

        if file_type.is_dir() {
            hasher.update(b"directory");
            update_hash_field(hasher, relative.as_bytes());
            hash_directory_entries(root, &path, hasher)?;
        } else if file_type.is_file() {
            hasher.update(b"file");
            update_hash_field(hasher, relative.as_bytes());
            let mut file = File::open(&path)
                .map_err(|error| format!("Could not open {}: {error}", path.display()))?;
            let size = file
                .metadata()
                .map_err(|error| format!("Could not inspect {}: {error}", path.display()))?
                .len();
            hasher.update(size.to_le_bytes());
            let mut buffer = [0_u8; 16 * 1024];

            loop {
                let read = file
                    .read(&mut buffer)
                    .map_err(|error| format!("Could not read {}: {error}", path.display()))?;
                if read == 0 {
                    break;
                }
                hasher.update(&buffer[..read]);
            }
        } else {
            return Err(format!(
                "{} is not a regular file or directory",
                path.display()
            ));
        }
    }

    Ok(())
}

fn directory_digest(root: &Path) -> Result<String, String> {
    if !root.is_dir() {
        return Err(format!("{} is not a directory", root.display()));
    }

    let mut hasher = Sha256::new();
    hash_directory_entries(root, root, &mut hasher)?;
    let digest = hasher.finalize();
    let mut encoded = String::with_capacity(digest.len() * 2);
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in digest {
        encoded.push(HEX[(byte >> 4) as usize] as char);
        encoded.push(HEX[(byte & 0x0f) as usize] as char);
    }
    Ok(encoded)
}

fn valid_digest(digest: &str) -> bool {
    digest.len() == 64
        && digest
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn install_ownership(target: &Path) -> InstallOwnership {
    let Ok(contents) = fs::read_to_string(target.join(MARKER_FILE)) else {
        return InstallOwnership::Unmanaged;
    };

    if contents == LEGACY_MARKER_CONTENTS {
        return InstallOwnership::Legacy;
    }

    match serde_json::from_str::<InstallMarker>(&contents) {
        Ok(marker)
            if marker.version == MARKER_VERSION
                && marker.source == CATALOG_SOURCE
                && valid_digest(&marker.skill_digest) =>
        {
            InstallOwnership::Managed(marker)
        }
        _ => InstallOwnership::Unmanaged,
    }
}

fn installation_status(target: &Path, catalog_digest: Option<&str>) -> SkillStatus {
    if !target.exists() {
        return SkillStatus::Available;
    }

    match install_ownership(target) {
        InstallOwnership::Unmanaged => SkillStatus::Conflict,
        InstallOwnership::Legacy => match catalog_digest {
            Some(_) => SkillStatus::UpdateAvailable,
            None => SkillStatus::Removed,
        },
        InstallOwnership::Managed(marker) => match directory_digest(target) {
            Ok(installed_digest) if installed_digest == marker.skill_digest => match catalog_digest
            {
                Some(digest) if digest == installed_digest => SkillStatus::Installed,
                Some(_) => SkillStatus::UpdateAvailable,
                None => SkillStatus::Removed,
            },
            _ => SkillStatus::Modified,
        },
    }
}

fn catalog_skills(root: &Path) -> Result<BTreeMap<String, CatalogSkill>, String> {
    let entries = fs::read_dir(root)
        .map_err(|error| format!("Could not read catalog {}: {error}", root.display()))?;
    let mut skills = BTreeMap::new();

    for entry in entries {
        let entry =
            entry.map_err(|error| format!("Could not read catalog {}: {error}", root.display()))?;
        let file_type = entry
            .file_type()
            .map_err(|error| format!("Could not inspect {}: {error}", entry.path().display()))?;
        if !file_type.is_dir() {
            continue;
        }

        let name = entry
            .file_name()
            .to_str()
            .ok_or_else(|| "A catalog skill has a non-UTF-8 name.".to_string())?
            .to_string();
        validate_skill_name(&name)?;
        let path = entry.path();

        if path.join(MARKER_FILE).exists() {
            return Err(format!(
                "{} contains the reserved marker file",
                path.display()
            ));
        }

        let (declared_name, description) = skill_frontmatter(&path)?;
        if declared_name != name {
            return Err(format!(
                "{} declares the name {declared_name}, expected {name}",
                path.join("SKILL.md").display()
            ));
        }

        let digest = directory_digest(&path)?;
        skills.insert(
            name.clone(),
            CatalogSkill {
                name,
                description,
                digest,
            },
        );
    }

    if skills.is_empty() {
        return Err("The skillbook catalog does not contain any skills.".to_string());
    }

    Ok(skills)
}

fn state_at(
    home: &Path,
    catalog: &Path,
    catalog_status: CatalogStatus,
    catalog_message: Option<String>,
) -> Result<AppState, String> {
    let root = install_root(home);
    let catalog_skills = catalog_skills(catalog)?;
    let mut skills = catalog_skills
        .values()
        .map(|skill| Skill {
            name: skill.name.clone(),
            description: skill.description.clone(),
            status: installation_status(&root.join(&skill.name), Some(&skill.digest)),
        })
        .collect::<Vec<_>>();

    if root.is_dir() {
        for entry in fs::read_dir(&root)
            .map_err(|error| format!("Could not read {}: {error}", root.display()))?
        {
            let entry =
                entry.map_err(|error| format!("Could not read {}: {error}", root.display()))?;
            if !entry
                .file_type()
                .map_err(|error| format!("Could not inspect {}: {error}", entry.path().display()))?
                .is_dir()
            {
                continue;
            }

            let Some(name) = entry.file_name().to_str().map(str::to_string) else {
                continue;
            };
            if validate_skill_name(&name).is_err() || catalog_skills.contains_key(&name) {
                continue;
            }
            if matches!(
                install_ownership(&entry.path()),
                InstallOwnership::Unmanaged
            ) {
                continue;
            }

            skills.push(Skill {
                name,
                description: "This skill is no longer available in skillbook.".to_string(),
                status: installation_status(&entry.path(), None),
            });
        }
    }

    skills.sort_by(|left, right| left.name.cmp(&right.name));

    Ok(AppState {
        install_root: root.display().to_string(),
        catalog_source: CATALOG_SOURCE,
        catalog_status,
        catalog_message,
        skills,
    })
}

fn archive_skill_path(path: &Path) -> Result<Option<PathBuf>, String> {
    let mut components = Vec::new();

    for component in path.components() {
        let Component::Normal(part) = component else {
            return Err(format!(
                "Archive contains an unsafe path: {}",
                path.display()
            ));
        };
        components.push(part);
    }

    if components.len() < 3 || components[1] != OsStr::new("skills") {
        return Ok(None);
    }

    let skill_name = components[2]
        .to_str()
        .ok_or_else(|| format!("Archive path is not UTF-8: {}", path.display()))?;
    validate_skill_name(skill_name)?;

    let mut relative = PathBuf::from(skill_name);
    for component in &components[3..] {
        relative.push(component);
    }

    Ok(Some(relative))
}

fn extract_catalog_archive(bytes: &[u8], target: &Path) -> Result<(), String> {
    fs::create_dir_all(target)
        .map_err(|error| format!("Could not create {}: {error}", target.display()))?;
    let decoder = GzDecoder::new(Cursor::new(bytes));
    let mut archive = tar::Archive::new(decoder);
    let entries = archive
        .entries()
        .map_err(|error| format!("Could not read the skillbook archive: {error}"))?;
    let mut extracted_bytes = 0_u64;
    let mut extracted_files = 0_usize;

    for entry in entries {
        let mut entry =
            entry.map_err(|error| format!("Could not read the skillbook archive: {error}"))?;
        let archive_path = entry
            .path()
            .map_err(|error| format!("Archive contains an invalid path: {error}"))?
            .into_owned();
        let Some(relative) = archive_skill_path(&archive_path)? else {
            continue;
        };
        let destination = target.join(relative);
        let entry_type = entry.header().entry_type();

        if entry_type.is_dir() {
            fs::create_dir_all(&destination)
                .map_err(|error| format!("Could not create {}: {error}", destination.display()))?;
            continue;
        }
        if !entry_type.is_file() {
            return Err(format!(
                "Archive entry {} is not a regular file or directory",
                archive_path.display()
            ));
        }

        extracted_files += 1;
        if extracted_files > MAX_CATALOG_FILES {
            return Err(format!(
                "The skillbook archive contains more than {MAX_CATALOG_FILES} skill files."
            ));
        }
        extracted_bytes = extracted_bytes
            .checked_add(entry.size())
            .ok_or_else(|| "The skillbook archive is too large.".to_string())?;
        if extracted_bytes > MAX_EXTRACTED_BYTES {
            return Err(format!(
                "The skillbook archive expands beyond {} MB.",
                MAX_EXTRACTED_BYTES / 1024 / 1024
            ));
        }

        let parent = destination
            .parent()
            .ok_or_else(|| format!("{} has no parent", destination.display()))?;
        fs::create_dir_all(parent)
            .map_err(|error| format!("Could not create {}: {error}", parent.display()))?;
        let mut output = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&destination)
            .map_err(|error| format!("Could not create {}: {error}", destination.display()))?;
        std::io::copy(&mut entry, &mut output)
            .map_err(|error| format!("Could not write {}: {error}", destination.display()))?;
        output
            .flush()
            .map_err(|error| format!("Could not write {}: {error}", destination.display()))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;

            let mode = entry.header().mode().map_err(|error| {
                format!(
                    "Could not read {} permissions: {error}",
                    archive_path.display()
                )
            })?;
            fs::set_permissions(&destination, fs::Permissions::from_mode(mode & 0o777)).map_err(
                |error| {
                    format!(
                        "Could not set {} permissions: {error}",
                        destination.display()
                    )
                },
            )?;
        }
    }

    catalog_skills(target)?;
    Ok(())
}

fn temporary_path(parent: &Path, label: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    parent.join(format!(".{label}-{}-{nonce}", std::process::id()))
}

fn activate_catalog(staging: &Path, cache_base: &Path) -> Result<(), String> {
    let current = catalog_dir(cache_base);
    if !current.exists() {
        return fs::rename(staging, &current)
            .map_err(|error| format!("Could not activate the skillbook catalog: {error}"));
    }

    let backup = temporary_path(cache_base, "catalog-previous");
    fs::rename(&current, &backup).map_err(|error| {
        format!("Could not prepare the existing catalog for replacement: {error}")
    })?;

    if let Err(error) = fs::rename(staging, &current) {
        let restore = fs::rename(&backup, &current);
        return match restore {
            Ok(()) => Err(format!("Could not activate the new skillbook catalog: {error}")),
            Err(restore_error) => Err(format!(
                "Could not activate the new skillbook catalog ({error}) or restore the previous catalog ({restore_error})."
            )),
        };
    }

    fs::remove_dir_all(&backup).map_err(|error| {
        format!("The catalog updated, but its previous cache could not be removed: {error}")
    })
}

fn refresh_catalog(cache_base: &Path, bytes: &[u8]) -> Result<(), String> {
    fs::create_dir_all(cache_base)
        .map_err(|error| format!("Could not create {}: {error}", cache_base.display()))?;
    let staging = temporary_path(cache_base, "catalog-downloading");
    let result = extract_catalog_archive(bytes, &staging)
        .and_then(|()| activate_catalog(&staging, cache_base));

    if staging.exists() {
        let _ = fs::remove_dir_all(&staging);
    }

    result
}

async fn download_catalog() -> Result<Vec<u8>, String> {
    let client = reqwest::Client::builder()
        .https_only(true)
        .timeout(Duration::from_secs(30))
        .user_agent(format!("skill-manager/{}", env!("CARGO_PKG_VERSION")))
        .build()
        .map_err(|error| format!("Could not configure the skillbook download: {error}"))?;
    let response = client
        .get(CATALOG_ARCHIVE_URL)
        .send()
        .await
        .map_err(|error| format!("Could not download skillbook: {error}"))?
        .error_for_status()
        .map_err(|error| format!("GitHub rejected the skillbook download: {error}"))?;

    if response
        .content_length()
        .is_some_and(|length| length > MAX_ARCHIVE_BYTES)
    {
        return Err(format!(
            "The skillbook archive exceeds {} MB.",
            MAX_ARCHIVE_BYTES / 1024 / 1024
        ));
    }

    let bytes = response
        .bytes()
        .await
        .map_err(|error| format!("Could not read the skillbook download: {error}"))?;
    if bytes.len() as u64 > MAX_ARCHIVE_BYTES {
        return Err(format!(
            "The skillbook archive exceeds {} MB.",
            MAX_ARCHIVE_BYTES / 1024 / 1024
        ));
    }

    Ok(bytes.to_vec())
}

fn copy_directory(source: &Path, target: &Path) -> Result<(), String> {
    fs::create_dir(target)
        .map_err(|error| format!("Could not create {}: {error}", target.display()))?;
    let mut entries = fs::read_dir(source)
        .map_err(|error| format!("Could not read {}: {error}", source.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("Could not read {}: {error}", source.display()))?;
    entries.sort_by_key(fs::DirEntry::file_name);

    for entry in entries {
        let source_path = entry.path();
        let destination = target.join(entry.file_name());
        let file_type = entry
            .file_type()
            .map_err(|error| format!("Could not inspect {}: {error}", source_path.display()))?;

        if file_type.is_dir() {
            copy_directory(&source_path, &destination)?;
        } else if file_type.is_file() {
            fs::copy(&source_path, &destination).map_err(|error| {
                format!(
                    "Could not copy {} to {}: {error}",
                    source_path.display(),
                    destination.display()
                )
            })?;
        } else {
            return Err(format!(
                "{} is not a regular file or directory",
                source_path.display()
            ));
        }
    }

    Ok(())
}

fn write_install_marker(target: &Path, digest: &str) -> Result<(), String> {
    let marker = InstallMarker {
        version: MARKER_VERSION,
        source: CATALOG_SOURCE.to_string(),
        skill_digest: digest.to_string(),
    };
    let mut contents = serde_json::to_string_pretty(&marker)
        .map_err(|error| format!("Could not create the ownership marker: {error}"))?;
    contents.push('\n');
    fs::write(target.join(MARKER_FILE), contents)
        .map_err(|error| format!("Could not write the ownership marker: {error}"))
}

fn install_at(home: &Path, catalog: &Path, name: &str) -> Result<(), String> {
    validate_skill_name(name)?;
    let source = catalog.join(name);
    if !source.is_dir() {
        return Err(format!("Unknown skill: {name}"));
    }

    let (declared_name, _) = skill_frontmatter(&source)?;
    if declared_name != name {
        return Err(format!("{name} has invalid catalog metadata."));
    }
    let digest = directory_digest(&source)?;
    let root = install_root(home);
    let target = root.join(name);

    if target.exists() {
        match installation_status(&target, Some(&digest)) {
            SkillStatus::Installed => return Err(format!("{name} is already installed.")),
            SkillStatus::UpdateAvailable => {}
            SkillStatus::Modified => {
                return Err(format!(
                    "{} contains local changes. Skill Manager will not overwrite it.",
                    target.display()
                ));
            }
            _ => {
                return Err(format!(
                    "{} already exists. Skill Manager will not overwrite it.",
                    target.display()
                ));
            }
        }
    }

    fs::create_dir_all(&root)
        .map_err(|error| format!("Could not create {}: {error}", root.display()))?;
    let staging = temporary_path(&root, &format!("{name}-installing"));
    let result = (|| {
        copy_directory(&source, &staging)?;
        write_install_marker(&staging, &digest)?;

        if !target.exists() {
            return fs::rename(&staging, &target)
                .map_err(|error| format!("Could not finish installing {name}: {error}"));
        }

        let backup = temporary_path(&root, &format!("{name}-previous"));
        fs::rename(&target, &backup)
            .map_err(|error| format!("Could not prepare {name} for update: {error}"))?;
        if let Err(error) = fs::rename(&staging, &target) {
            let restore = fs::rename(&backup, &target);
            return match restore {
                Ok(()) => Err(format!("Could not finish updating {name}: {error}")),
                Err(restore_error) => Err(format!(
                    "Could not finish updating {name} ({error}) or restore the installed copy ({restore_error})."
                )),
            };
        }
        fs::remove_dir_all(&backup).map_err(|error| {
            format!("{name} updated, but its previous copy could not be removed: {error}")
        })
    })();

    if staging.exists() {
        let _ = fs::remove_dir_all(&staging);
    }

    result
}

fn uninstall_at(home: &Path, name: &str) -> Result<(), String> {
    validate_skill_name(name)?;
    let target = install_root(home).join(name);

    if !target.exists() {
        return Err(format!("{name} is not installed."));
    }

    match install_ownership(&target) {
        InstallOwnership::Unmanaged => {
            return Err(format!(
                "{} is not managed by Skill Manager. It was not removed.",
                target.display()
            ));
        }
        InstallOwnership::Legacy => {}
        InstallOwnership::Managed(marker) => {
            let digest = directory_digest(&target)?;
            if digest != marker.skill_digest {
                return Err(format!(
                    "{} contains local changes. It was not removed.",
                    target.display()
                ));
            }
        }
    }

    fs::remove_dir_all(&target).map_err(|error| format!("Could not uninstall {name}: {error}"))
}

async fn load_app_state() -> Result<AppState, String> {
    let home = home_dir()?;
    let cache_base = cache_base_dir()?;
    let catalog = catalog_dir(&cache_base);

    match download_catalog()
        .await
        .and_then(|bytes| refresh_catalog(&cache_base, &bytes))
    {
        Ok(()) => state_at(&home, &catalog, CatalogStatus::Fresh, None),
        Err(error) if catalog.is_dir() => state_at(
            &home,
            &catalog,
            CatalogStatus::Cached,
            Some(format!(
                "Could not refresh from GitHub. Using the last downloaded catalog. {error}"
            )),
        ),
        Err(error) => Err(format!(
            "Could not load the skillbook catalog and no cached copy is available. {error}"
        )),
    }
}

#[tauri::command]
async fn get_app_state(runtime: State<'_, RuntimeState>) -> Result<AppState, String> {
    let _guard = runtime.catalog_lock.lock().await;
    load_app_state().await
}

#[tauri::command]
async fn install_skill(runtime: State<'_, RuntimeState>, name: &str) -> Result<(), String> {
    let _guard = runtime.catalog_lock.lock().await;
    install_at(&home_dir()?, &catalog_dir(&cache_base_dir()?), name)
}

#[tauri::command]
async fn uninstall_skill(runtime: State<'_, RuntimeState>, name: &str) -> Result<(), String> {
    let _guard = runtime.catalog_lock.lock().await;
    uninstall_at(&home_dir()?, name)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(RuntimeState::default())
        .invoke_handler(tauri::generate_handler![
            get_app_state,
            install_skill,
            uninstall_skill
        ])
        .run(tauri::generate_context!())
        .expect("error while running Tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;
    use flate2::{write::GzEncoder, Compression};
    use tar::{Builder, Header};

    fn write_skill(catalog: &Path, name: &str, description: &str) {
        let skill = catalog.join(name);
        fs::create_dir_all(&skill).expect("skill directory");
        fs::write(
            skill.join("SKILL.md"),
            format!("---\nname: {name}\ndescription: \"{description}\"\n---\n\n# {name}\n"),
        )
        .expect("skill contents");
    }

    fn test_state(home: &Path, catalog: &Path) -> AppState {
        state_at(home, catalog, CatalogStatus::Fresh, None).expect("state should load")
    }

    fn test_archive() -> Vec<u8> {
        let encoder = GzEncoder::new(Vec::new(), Compression::default());
        let mut builder = Builder::new(encoder);
        let contents =
            b"---\nname: remote-skill\ndescription: \"Downloaded skill\"\n---\n\n# Remote\n";
        let mut header = Header::new_gnu();
        header.set_size(contents.len() as u64);
        header.set_mode(0o644);
        header.set_cksum();
        builder
            .append_data(
                &mut header,
                "skillbook-main/skills/remote-skill/SKILL.md",
                &contents[..],
            )
            .expect("archive entry");
        builder
            .into_inner()
            .expect("archive")
            .finish()
            .expect("compressed archive")
    }

    #[test]
    fn catalog_reads_skills_from_a_directory() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "python-standards", "Strict Python");
        write_skill(catalog.path(), "git-ops", "Safe Git");

        let state = test_state(home.path(), catalog.path());

        assert_eq!(state.skills.len(), 2);
        assert_eq!(state.skills[0].name, "git-ops");
        assert_eq!(state.skills[1].name, "python-standards");
        assert!(state
            .skills
            .iter()
            .all(|skill| skill.status == SkillStatus::Available));
    }

    #[test]
    fn install_and_uninstall_round_trip() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Test skill");
        let target = install_root(home.path()).join("hello-world");

        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");

        assert!(target.join("SKILL.md").is_file());
        assert!(target.join(MARKER_FILE).is_file());
        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Installed
        );

        uninstall_at(home.path(), "hello-world").expect("uninstall should work");
        assert!(!target.exists());
    }

    #[test]
    fn update_replaces_an_unmodified_managed_skill() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Version one");
        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");
        write_skill(catalog.path(), "hello-world", "Version two");

        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::UpdateAvailable
        );

        install_at(home.path(), catalog.path(), "hello-world").expect("update should work");
        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Installed
        );
        assert!(
            fs::read_to_string(install_root(home.path()).join("hello-world/SKILL.md"))
                .expect("installed skill")
                .contains("Version two")
        );
    }

    #[test]
    fn modified_install_is_not_overwritten_or_removed() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Test skill");
        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");
        let installed = install_root(home.path()).join("hello-world/SKILL.md");
        fs::write(&installed, "local changes").expect("local edit");

        assert_eq!(
            test_state(home.path(), catalog.path()).skills[0].status,
            SkillStatus::Modified
        );
        assert!(install_at(home.path(), catalog.path(), "hello-world").is_err());
        assert!(uninstall_at(home.path(), "hello-world").is_err());
        assert_eq!(
            fs::read_to_string(installed).expect("local edit remains"),
            "local changes"
        );
    }

    #[test]
    fn removed_managed_skill_remains_available_for_uninstall() {
        let home = tempfile::tempdir().expect("temporary home");
        let catalog = tempfile::tempdir().expect("temporary catalog");
        write_skill(catalog.path(), "hello-world", "Test skill");
        install_at(home.path(), catalog.path(), "hello-world").expect("install should work");
        fs::remove_dir_all(catalog.path().join("hello-world")).expect("remove from catalog");
        write_skill(catalog.path(), "other-skill", "Keeps catalog valid");

        let state = test_state(home.path(), catalog.path());
        let removed = state
            .skills
            .iter()
            .find(|skill| skill.name == "hello-world")
            .expect("removed skill remains visible");

        assert_eq!(removed.status, SkillStatus::Removed);
        uninstall_at(home.path(), "hello-world").expect("removed skill can be uninstalled");
    }

    #[test]
    fn extracts_and_validates_a_skillbook_archive() {
        let target = tempfile::tempdir().expect("temporary extraction");

        extract_catalog_archive(&test_archive(), target.path()).expect("archive should extract");

        let skills = catalog_skills(target.path()).expect("catalog should validate");
        assert!(skills.contains_key("remote-skill"));
    }

    #[test]
    fn uninstall_refuses_an_unmanaged_directory() {
        let home = tempfile::tempdir().expect("temporary home");
        let target = install_root(home.path()).join("hello-world");
        fs::create_dir_all(&target).expect("unmanaged directory");
        fs::write(target.join("SKILL.md"), "keep me").expect("unmanaged skill");

        let error =
            uninstall_at(home.path(), "hello-world").expect_err("uninstall should be refused");

        assert!(error.contains("not managed"));
        assert!(target.join("SKILL.md").is_file());
    }
}
