use include_dir::{include_dir, Dir, DirEntry};
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

static SKILLS: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/../skills");
const MARKER_FILE: &str = ".skill-manager-managed";
const MARKER_CONTENTS: &str = "Managed by Skill Manager. Do not edit this file.\n";

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct Skill {
    name: String,
    description: String,
    status: SkillStatus,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "lowercase")]
enum SkillStatus {
    Available,
    Installed,
    Conflict,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct AppState {
    install_root: String,
    skills: Vec<Skill>,
}

fn home_dir() -> Result<PathBuf, String> {
    dirs::home_dir().ok_or_else(|| "Could not find your home directory.".to_string())
}

fn install_root(home: &Path) -> PathBuf {
    home.join(".agents").join("skills")
}

fn validate_skill_name(name: &str) -> Result<(), String> {
    let valid = !name.is_empty()
        && name
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
        && !name.starts_with('-')
        && !name.ends_with('-')
        && !name.contains("--");

    if valid {
        Ok(())
    } else {
        Err(format!("Invalid skill name: {name}"))
    }
}

fn skill_dir(name: &str) -> Result<&'static Dir<'static>, String> {
    validate_skill_name(name)?;
    SKILLS
        .get_dir(name)
        .ok_or_else(|| format!("Unknown skill: {name}"))
}

fn frontmatter_value(contents: &str, key: &str) -> Option<String> {
    let frontmatter = contents.strip_prefix("---\n")?.split_once("\n---")?.0;
    let prefix = format!("{key}:");

    frontmatter.lines().find_map(|line| {
        line.strip_prefix(&prefix)
            .map(str::trim)
            .map(|value| value.trim_matches(['"', '\'']).to_string())
            .filter(|value| !value.is_empty())
    })
}

fn skill_description(skill: &Dir<'_>) -> Result<String, String> {
    let file = skill
        .entries()
        .iter()
        .find_map(|entry| match entry {
            DirEntry::File(file)
                if file
                    .path()
                    .file_name()
                    .is_some_and(|name| name == "SKILL.md") =>
            {
                Some(file)
            }
            _ => None,
        })
        .ok_or_else(|| format!("{} is missing SKILL.md", skill.path().display()))?;
    let contents = file
        .contents_utf8()
        .ok_or_else(|| format!("{} is not UTF-8", file.path().display()))?;

    frontmatter_value(contents, "description")
        .ok_or_else(|| format!("{} is missing a description", file.path().display()))
}

fn status_for(target: &Path) -> SkillStatus {
    if !target.exists() {
        return SkillStatus::Available;
    }

    match fs::read_to_string(target.join(MARKER_FILE)) {
        Ok(contents) if contents == MARKER_CONTENTS => SkillStatus::Installed,
        _ => SkillStatus::Conflict,
    }
}

fn state_at(home: &Path) -> Result<AppState, String> {
    let root = install_root(home);
    let mut skills = SKILLS
        .dirs()
        .map(|skill| {
            let name = skill
                .path()
                .file_name()
                .and_then(|name| name.to_str())
                .ok_or_else(|| "A bundled skill has an invalid name.".to_string())?
                .to_string();
            validate_skill_name(&name)?;

            Ok(Skill {
                description: skill_description(skill)?,
                status: status_for(&root.join(&name)),
                name,
            })
        })
        .collect::<Result<Vec<_>, String>>()?;
    skills.sort_by(|left, right| left.name.cmp(&right.name));

    Ok(AppState {
        install_root: root.display().to_string(),
        skills,
    })
}

fn copy_embedded_dir(source: &Dir<'_>, target: &Path) -> Result<(), String> {
    fs::create_dir_all(target).map_err(|error| {
        format!(
            "Could not create install directory {}: {error}",
            target.display()
        )
    })?;

    for entry in source.entries() {
        let name = entry
            .path()
            .file_name()
            .ok_or_else(|| "A bundled file has an invalid path.".to_string())?;
        let destination = target.join(name);

        match entry {
            DirEntry::Dir(directory) => copy_embedded_dir(directory, &destination)?,
            DirEntry::File(file) => fs::write(&destination, file.contents())
                .map_err(|error| format!("Could not write {}: {error}", destination.display()))?,
        }
    }

    Ok(())
}

fn temporary_install_path(root: &Path, name: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    root.join(format!(".{name}.installing-{}-{nonce}", std::process::id()))
}

fn install_at(home: &Path, name: &str) -> Result<(), String> {
    let source = skill_dir(name)?;
    let root = install_root(home);
    let target = root.join(name);

    if target.exists() {
        return Err(format!(
            "{} already exists. Skill Manager will not overwrite it.",
            target.display()
        ));
    }

    fs::create_dir_all(&root)
        .map_err(|error| format!("Could not create {}: {error}", root.display()))?;
    let temporary = temporary_install_path(&root, name);

    let result = (|| {
        copy_embedded_dir(source, &temporary)?;
        fs::write(temporary.join(MARKER_FILE), MARKER_CONTENTS)
            .map_err(|error| format!("Could not write the ownership marker: {error}"))?;
        fs::rename(&temporary, &target)
            .map_err(|error| format!("Could not finish installing {name}: {error}"))
    })();

    if result.is_err() {
        let _ = fs::remove_dir_all(&temporary);
    }

    result
}

fn uninstall_at(home: &Path, name: &str) -> Result<(), String> {
    skill_dir(name)?;
    let target = install_root(home).join(name);

    if !target.exists() {
        return Err(format!("{name} is not installed."));
    }

    match fs::read_to_string(target.join(MARKER_FILE)) {
        Ok(contents) if contents == MARKER_CONTENTS => {}
        _ => {
            return Err(format!(
                "{} is not managed by Skill Manager. It was not removed.",
                target.display()
            ));
        }
    }

    fs::remove_dir_all(&target).map_err(|error| format!("Could not uninstall {name}: {error}"))
}

#[tauri::command]
fn get_app_state() -> Result<AppState, String> {
    state_at(&home_dir()?)
}

#[tauri::command]
fn install_skill(name: &str) -> Result<(), String> {
    install_at(&home_dir()?, name)
}

#[tauri::command]
fn uninstall_skill(name: &str) -> Result<(), String> {
    uninstall_at(&home_dir()?, name)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            get_app_state,
            install_skill,
            uninstall_skill
        ])
        .run(tauri::generate_context!())
        .expect("error while running Tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_contains_the_bundled_skill() {
        let home = tempfile::tempdir().expect("temporary home");
        let state = state_at(home.path()).expect("catalog should load");

        assert_eq!(state.skills.len(), 1);
        assert_eq!(state.skills[0].name, "hello-world");
        assert!(matches!(state.skills[0].status, SkillStatus::Available));
    }

    #[test]
    fn install_and_uninstall_round_trip() {
        let home = tempfile::tempdir().expect("temporary home");
        let target = install_root(home.path()).join("hello-world");

        install_at(home.path(), "hello-world").expect("install should work");
        assert!(target.join("SKILL.md").is_file());
        assert!(target.join(MARKER_FILE).is_file());
        assert!(matches!(
            state_at(home.path()).expect("state").skills[0].status,
            SkillStatus::Installed
        ));

        uninstall_at(home.path(), "hello-world").expect("uninstall should work");
        assert!(!target.exists());
    }

    #[test]
    fn uninstall_refuses_an_unmanaged_directory() {
        let home = tempfile::tempdir().expect("temporary home");
        let target = install_root(home.path()).join("hello-world");
        fs::create_dir_all(&target).expect("unmanaged directory");
        fs::write(target.join("SKILL.md"), "keep me").expect("unmanaged skill");

        let error =
            uninstall_at(home.path(), "hello-world").expect_err("uninstall should be refused");

        assert!(error.contains("not managed"));
        assert!(target.join("SKILL.md").is_file());
    }
}
